package com.ferullogaming.craftingdead.item;

import java.util.ArrayList;

import com.ferullogaming.craftingdead.CDAftermath;
import com.ferullogaming.craftingdead.CraftingEvents;
import com.ferullogaming.craftingdead.client.anim.GunAnimationPistolFired;
import com.ferullogaming.craftingdead.client.anim.GunAnimationReloadP90;
import com.ferullogaming.craftingdead.client.anim.GunAnimationRifleFired;
import com.ferullogaming.craftingdead.client.anim.GunAnimationSMGFired;
import com.ferullogaming.craftingdead.client.model.ModelBackpackGunbag;
import com.ferullogaming.craftingdead.client.model.ModelBackpackLarge;
import com.ferullogaming.craftingdead.client.model.ModelBackpackMedium;
import com.ferullogaming.craftingdead.client.model.ModelBackpackSmall;
import com.ferullogaming.craftingdead.client.model.ModelTacticalVest;
import com.ferullogaming.craftingdead.client.model.guns.ModelAKM10Rnd;
import com.ferullogaming.craftingdead.client.model.guns.ModelAKM30Rnd;
import com.ferullogaming.craftingdead.client.model.guns.ModelAS50Clip;
import com.ferullogaming.craftingdead.client.model.guns.ModelFNFALClip;
import com.ferullogaming.craftingdead.client.model.guns.ModelG18Clip;
import com.ferullogaming.craftingdead.client.model.guns.ModelM107Clip;
import com.ferullogaming.craftingdead.client.model.guns.ModelM1911Clip;
import com.ferullogaming.craftingdead.client.model.guns.ModelM1GarandClip;
import com.ferullogaming.craftingdead.client.model.guns.ModelM240BClip;
import com.ferullogaming.craftingdead.client.model.guns.ModelM9Clip;
import com.ferullogaming.craftingdead.client.model.guns.ModelMAC10Clip;
import com.ferullogaming.craftingdead.client.model.guns.ModelMP5A4;
import com.ferullogaming.craftingdead.client.model.guns.ModelP90Clip;
import com.ferullogaming.craftingdead.client.model.guns.ModelSporter22Clip;
import com.ferullogaming.craftingdead.client.model.guns.ModelStanag20rnd;
import com.ferullogaming.craftingdead.client.model.guns.ModelStanag30rnd;
import com.ferullogaming.craftingdead.client.model.guns.ModelStanagBox;
import com.ferullogaming.craftingdead.client.model.guns.ModelStanagDrum;
import com.ferullogaming.craftingdead.client.model.guns.ModelTrenchGunShell;
import com.ferullogaming.craftingdead.client.render.RenderBackpackGunbag;
import com.ferullogaming.craftingdead.client.render.RenderBackpackLarge;
import com.ferullogaming.craftingdead.client.render.RenderBackpackMedium;
import com.ferullogaming.craftingdead.client.render.RenderBackpackSmall;
import com.ferullogaming.craftingdead.client.render.RenderTacticalVest;
import com.ferullogaming.craftingdead.client.render.guns.RenderAKM;
import com.ferullogaming.craftingdead.client.render.guns.RenderAS50;
import com.ferullogaming.craftingdead.client.render.guns.RenderFNFAL;
import com.ferullogaming.craftingdead.client.render.guns.RenderG18;
import com.ferullogaming.craftingdead.client.render.guns.RenderM107;
import com.ferullogaming.craftingdead.client.render.guns.RenderM1911;
import com.ferullogaming.craftingdead.client.render.guns.RenderM1Garand;
import com.ferullogaming.craftingdead.client.render.guns.RenderM240B;
import com.ferullogaming.craftingdead.client.render.guns.RenderM4A1;
import com.ferullogaming.craftingdead.client.render.guns.RenderM9;
import com.ferullogaming.craftingdead.client.render.guns.RenderMAC10;
import com.ferullogaming.craftingdead.client.render.guns.RenderMP5A4;
import com.ferullogaming.craftingdead.client.render.guns.RenderP90;
import com.ferullogaming.craftingdead.client.render.guns.RenderScarh;
import com.ferullogaming.craftingdead.client.render.guns.RenderSporter;
import com.ferullogaming.craftingdead.client.render.guns.RenderTrenchGun;
import com.ferullogaming.craftingdead.client.render.hat.RenderHatArmyhelmet;
import com.ferullogaming.craftingdead.client.render.hat.RenderHatBunny;
import com.ferullogaming.craftingdead.client.render.hat.RenderHatFireman;
import com.ferullogaming.craftingdead.client.render.hat.RenderHatGasmask;
import com.ferullogaming.craftingdead.client.render.hat.RenderHatHardhat;
import com.ferullogaming.craftingdead.client.render.hat.RenderHatKnight;
import com.ferullogaming.craftingdead.client.render.hat.RenderHatNVGoggles;
import com.ferullogaming.craftingdead.client.render.hat.RenderHatPayday;
import com.ferullogaming.craftingdead.client.render.hat.RenderHatTophat;
import com.ferullogaming.craftingdead.item.gun.EnumFireMode;
import com.ferullogaming.craftingdead.item.gun.GunAttachment;
import com.ferullogaming.craftingdead.item.gun.GunPaint;
import com.ferullogaming.craftingdead.item.gun.ItemAmmo;
import com.ferullogaming.craftingdead.item.gun.ItemGun;
import com.ferullogaming.craftingdead.item.gun.ItemGunAttachment;
import com.ferullogaming.craftingdead.item.gun.ItemPaint;
import com.ferullogaming.craftingdead.item.potion.PotionManager;

import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;
import net.minecraft.block.Block;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.EnumAction;
import net.minecraft.item.EnumArmorMaterial;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.potion.Potion;
import net.minecraft.util.EnumChatFormatting;
import net.minecraftforge.common.EnumHelper;

public class ItemManager {
   public static CreativeTabs tabCraftingDead = new CreativeTabCraftingDead("cda");
   public static CreativeTabs tabCraftingDeadInventory = new CreativeTabCraftingDeadInventory("cdainv");
   public static final ArrayList whitelistedCraftingDeadItems = new ArrayList();
   private LootManager lootManager;
   private PotionManager potionManager;
   public ArrayList blueprintRecipes = new ArrayList();
   public static final int[] destroyableAxeIDs;
   public static final int[] destroyablePickaxeIDs;
   public static Item m4a1;
   public static Item scarh;
   public static Item akm;
   public static Item fnfal;
   public static Item m1911;
   public static Item g18;
   public static Item m9;
   public static Item mac10;
   public static Item p90;
   public static Item sporter22;
   public static Item m107;
   public static Item as50;
   public static Item m1garand;
   public static Item trenchgun;
   public static Item m240b;
   public static Item mp5a4;
   public static Item stanag20Rnd;
   public static Item stanag30Rnd;
   public static Item stanagDrum;
   public static Item stanagBox;
   public static Item akm10rnd;
   public static Item akm30rnd;
   public static Item fnfalAmmo;
   public static Item m1911Ammo;
   public static Item g18Ammo;
   public static Item m9Ammo;
   public static Item mac10Ammo;
   public static Item p90Ammo;
   public static Item sporter22Ammo;
   public static Item m107Ammo;
   public static Item m107AmmoAP;
   public static Item as50Ammo;
   public static Item as50AmmoAP;
   public static Item m1garandAmmo;
   public static Item trenchgunAmmo;
   public static Item m240bAmmo;
   public static Item mp5a4rnd;
   public static Item attachmentReddot;
   public static Item attachmentACOG;
   public static Item attachmentScope6x;
   public static Item attachmentScope12x;
   public static Item attachmentGrip;
   public static Item attachmentSupressor;
   public static Item attachmentMuzzleBrake;
   public static Item attachmentBipod;
   public static Item crowbar;
   public static Item bat;
   public static Item pipe;
   public static Item rustypipe;
   public static Item ninjasword;
   public static Item fireaxe;
   public static Item chainsaw;
   public static Item bowie;
   public static Item golfclub;
   public static Item nightstick;
   public static Item sludgehammer;
   public static Item batNail;
   public static Item shovel;
   public static Item hatchet;
   public static Item broadsword;
   public static Item machete;
   public static Item scytheweapon;
   public static Item scythe;
   public static Item pickaxe;
   public static Item bostaff;
   public static Item wrench;
   public static Item fryingPan;
   public static Item boltCutters;
   public static Item combatKnife;
   public static Item steelBat;
   public static Item cleaver;
   public static Item screwdriver;
   public static Item canOpener;
   public static Item powerbar;
   public static Item candybar;
   public static Item cereal;
   public static Item cannedBeans;
   public static Item cannedBeansOpen;
   public static Item cannedTuna;
   public static Item cannedTunaOpen;
   public static Item cannedPeach;
   public static Item cannedPeachOpen;
   public static Item mre;
   public static Item orange;
   public static Item rottenOrange;
   public static Item pear;
   public static Item rottenPear;
   public static Item cannedPasta;
   public static Item cannedPastaOpen;
   public static Item rice;
   public static Item apple;
   public static Item rottenApple;
   public static Item cannedBacon;
   public static Item cannedBaconOpen;
   public static Item noodles;
   public static Item watermelon;
   public static Item rottenWatermelon;
   public static Item cannedCorn;
   public static Item cannedCornOpen;
   public static Item blueberry;
   public static Item rottenBlueberry;
   public static Item raspberry;
   public static Item rottenRaspberry;
   public static Item cannedCustard;
   public static Item cannedCustardOpen;
   public static Item cannedPickles;
   public static Item cannedPicklesOpen;
   public static Item chips;
   public static Item chipsRanch;
   public static Item chipsCheese;
   public static Item chipsSalt;
   public static Item sodaColaEmpty;
   public static Item sodaCola;
   public static Item sodaDewEmpty;
   public static Item sodaDew;
   public static Item sodaPepeEmpty;
   public static Item sodaPepe;
   public static Item sodaOrangeEmpty;
   public static Item sodaOrange;
   public static Item iceteaEmpty;
   public static Item icetea;
   public static Item juiceEmpty;
   public static Item juice;
   public static Item waterbottleEmpty;
   public static Item waterbottle;
   public static Item milkEmpty;
   public static Item milk;
   public static Item milkRotten;
   public static Item watercanteenEmpty;
   public static Item watercanteen;
   public static Item flask;
   public static Item flaskEmpty;
   public static Item flasktea;
   public static Item flaskCoffee;
   public static Item backpackSmallRed;
   public static Item backpackSmallOrange;
   public static Item backpackSmallYellow;
   public static Item backpackSmallGreen;
   public static Item backpackSmallBlue;
   public static Item backpackSmallPurple;
   public static Item backpackMediumRed;
   public static Item backpackMediumOrange;
   public static Item backpackMediumYellow;
   public static Item backpackMediumGreen;
   public static Item backpackMediumBlue;
   public static Item backpackMediumPurple;
   public static Item backpackMediumGrey;
   public static Item backpackMediumBlack;
   public static Item backpackMediumGhillie;
   public static Item backpackMediumWhite;
   public static Item backpackLargeGrey;
   public static Item backpackLargeGreen;
   public static Item backpackLargeTan;
   public static Item backpackLargeBlack;
   public static Item backpackLargeGhillie;
   public static Item backpackGunBag;
   public static Item backpackGunBagGrey;
   public static Item tacvestGrey;
   public static Item tacvestTan;
   public static Item tacvestGreen;
   public static Item tacvestBlack;
   public static Item tacvestGhillie;
   public static Item riotVest;
   public static Item fsbVest;
   public static Item clothingGhillie;
   public static Item clothingGhillieFull;
   public static Item clothingDusk;
   public static Item clothingSwat;
   public static Item clothingArmy;
   public static Item clothingBusiness;
   public static Item clothingDoctor;
   public static Item clothingHazmat;
   public static Item clothingPolice;
   public static Item clothingSheriff;
   public static Item clothingArmyDesert;
   public static Item clothingFireman;
   public static Item clothingSpaceman;
   public static Item clothingJuggernaut;
   public static Item clothingCamo;
   public static Item clothingCasual;
   public static Item clothingSmart;
   public static Item clothingSpetsnaz;
   public static Item clothingBuilder;
   public static Item clothingredCheckered;
   public static Item clothingArmyWinter;
   public static Item clothingCombatBDU;
   public static Item clothingFSB;
   public static Item defaultArmorH;
   public static Item defaultArmorC;
   public static Item defaultArmorL;
   public static Item defaultArmorB;
   public static EnumArmorMaterial DEFAULT;
   public static Item stonePebble;
   public static Item logSplit;
   public static Item pvcPipe;
   public static Item rawExplosive;
   public static Item detonator;
   public static Item electronicRemote;
   public static Item c4;
   public static Item battery;
   public static Item lootcrateAlpha;
   public static Item lootcrateBravo;
   public static Item lootcrateCharlie;
   public static Item fuelTankBackpack;
   public static Item fuelTank;
   public static Item flameThrower;
   public static Item handcuffs;
   public static Item handcuffsKey;
   public static Item teaBag;
   public static Item coffee;
   public static Item rope;
   public static Item chalk;
   public static Item hatPayDayMask;
   public static Item hatBunny;
   public static Item hatTophat;
   public static Item hatArmyHelmet;
   public static Item hatArmyHelmetGrey;
   public static Item hatArmyHelmetGreen;
   public static Item hatPayDayMask2;
   public static Item hatGasmask;
   public static Item hatGhillie;
   public static Item hatHazmat;
   public static Item hatNVGoggles;
   public static Item hatDoctor;
   public static Item hatKnight;
   public static Item hatHardhatRed;
   public static Item hatHardhatOrange;
   public static Item hatHardhatYellow;
   public static Item hatHardhatGreen;
   public static Item hatHardhatBlue;
   public static Item hatFireman;
   public static Item hatFiremanBlack;
   public static Item hatMobCreeper;
   public static Item hatMobZombie;
   public static Item hatMobCow;
   public static Item hatMobPumpkin;
   public static Item hatRiot;
   public static Item hatSanta;
   public static Item hatMobSheep;
   public static Item hatCamoHelmet;
   public static Item hatSpetsnazHelmet;
   public static Item hatCombatBDU;
   public static Item hatFSB;
   public static Item paintAsmo;
   public static Item paintCyrex;
   public static Item paintVulcan;
   public static Item paintGem;
   public static Item paintFade;
   public static Item paintRuby;
   public static Item paintUV;
   public static Item paintCandyApple;
   public static Item grenadeFlash;
   public static Item grenadeDecoy;
   public static Item grenadeSmoke;
   public static Item grenadeFire;
   public static Item grenadeFrag;
   public static Item grenadePipeBomb;
   public static Item bloodbag;
   public static Item bloodbagEmpy;
   public static Item bandage;
   public static Item medpack;
   public static Item needle;
   public static Item needleMorphine;
   public static Item needleCure;
   public static Item bottleCure;
   public static Item ragDirty;
   public static Item ragClean;
   public static Item splint;
   public static Item bottleRBI;
   public static Item needleRBI;
   public static Item needleAdrenaline;
   public static Item bush;
   public static Item silver;
   public static Item gold;

   private void initItems() {
      stanag20Rnd = (new ItemAmmo(9050, 20)).setArmorPenetration(25.0D).setModel(new ModelStanag20rnd(), "stanag20rnd").setCDItemDisplayName("Магазин STANAG 20rnd").setCDItemTextureName("stanag20rnd");
      stanag30Rnd = (new ItemAmmo(9051, 30)).setArmorPenetration(25.0D).setModel(new ModelStanag30rnd(), "stanag30rnd").setCDItemDisplayName("Магазин STANAG 30rnd").setCDItemTextureName("stanag30rnd");
      stanagDrum = (new ItemAmmo(9052, 45)).setArmorPenetration(25.0D).setModel(new ModelStanagDrum(), "stanagdrum").setCDItemDisplayName("Магазин STANAG Drum").setCDItemTextureName("stanagdrum");
      stanagBox = (new ItemAmmo(9053, 85)).setArmorPenetration(25.0D).setModel(new ModelStanagBox(), "stanagbox").setCDItemDisplayName("Магазин STANAG Box").setCDItemTextureName("stanagbox");
      akm10rnd = (new ItemAmmo(9054, 10)).setArmorPenetration(30.0D).setModel(new ModelAKM10Rnd(), "akm10rnd").setCDItemDisplayName("Магазин AKM 10Rnd").setCDItemTextureName("akm10rnd");
      akm30rnd = (new ItemAmmo(9055, 30)).setArmorPenetration(30.0D).setModel(new ModelAKM30Rnd(), "akm30rnd").setCDItemDisplayName("Магазин AKM 30Rnd").setCDItemTextureName("akm30rnd");
      fnfalAmmo = (new ItemAmmo(9066, 20)).setArmorPenetration(50.0D).setModel(new ModelFNFALClip(), "fnfalmodel").setCDItemDisplayName("Магазин FN FAL").setCDItemTextureName("fnfalclip");
      m1911Ammo = (new ItemAmmo(9056, 7)).setModel(new ModelM1911Clip(), "g18ammo").setCDItemDisplayName("Магазин M1911").setCDItemTextureName("m1911clip");
      g18Ammo = (new ItemAmmo(9057, 20)).setModel(new ModelG18Clip(), "g18ammo").setCDItemDisplayName("Магазин G18").setCDItemTextureName("g18clip");
      m9Ammo = (new ItemAmmo(9065, 15)).setModel(new ModelM9Clip(), "m9model").setCDItemDisplayName("Магазин M9").setCDItemTextureName("m9clip");
      mac10Ammo = (new ItemAmmo(9058, 30)).setArmorPenetration(15.0D).setModel(new ModelMAC10Clip(), "mac10model").setCDItemDisplayName("Магазин MAC-10").setCDItemTextureName("mac10clip");
      p90Ammo = (new ItemAmmo(9059, 50)).setArmorPenetration(15.0D).setModel(new ModelP90Clip(), "p90model").setCDItemDisplayName("Магазин P90").setCDItemTextureName("p90clip");
      sporter22Ammo = (new ItemAmmo(9060, 30)).setModel(new ModelSporter22Clip(), "sporter22model").setCDItemDisplayName("Магазин Sporter 22").setCDItemTextureName("sporter22clip");
      m107Ammo = (new ItemAmmo(9061, 10)).setArmorPenetration(35.0D).setModel(new ModelM107Clip(), "m107model").setCDItemDisplayName("Магазин M107").setCDItemTextureName("m107clip");
      m107AmmoAP = (new ItemAmmo(9062, 6)).setArmorPenetration(95.0D).setModel(new ModelM107Clip(), "m107modelap").setCDItemDisplayName("Магазин M107 Бронепробивающий").setCDItemTextureName("m107clipap");
      as50Ammo = (new ItemAmmo(9063, 10)).setArmorPenetration(35.0D).setModel(new ModelAS50Clip(), "as50model").setCDItemDisplayName("Магазин AS50").setCDItemTextureName("as50clip");
      as50AmmoAP = (new ItemAmmo(9064, 5)).setArmorPenetration(95.0D).setModel(new ModelAS50Clip(), "as50modelap").setCDItemDisplayName("Магазин AS50 Бронепробивающий").setCDItemTextureName("as50clipap");
      m1garandAmmo = (new ItemAmmo(9067, 8)).setArmorPenetration(95.0D).setModel(new ModelM1GarandClip(), "m1garandmodel").setCDItemDisplayName("Магазин M1 Garand").setCDItemTextureName("m1garandclip");
      trenchgunAmmo = (new ItemAmmo(9068, 6)).setArmorPenetration(35.0D).setModel(new ModelTrenchGunShell(), "trenchgunmodel").setCDItemDisplayName("Дробь для Trench Gun").setCDItemTextureName("shotgunshells");
      m240bAmmo = (new ItemAmmo(9069, 150)).setArmorPenetration(70.0D).setModel(new ModelM240BClip(), "m240bmodel").setCDItemDisplayName("M240B Box Magazine").setCDItemTextureName("m240bclip");
      mp5a4rnd = (new ItemAmmo(9070, 30)).setArmorPenetration(20.0D).setModel(new ModelMP5A4(2 ), "mp5a4").setCDItemDisplayName("Магазин MP5A4").setCDItemTextureName("mp5a4rnd");
      attachmentReddot = (new ItemGunAttachment(9075)).setCDItemDisplayName("Прицел 'Красная точка'").setCDItemTextureName("reddot");
      attachmentACOG = (new ItemGunAttachment(9076)).setCDItemDisplayName("Улучшенный боевой оптический прицел").setCDItemTextureName("acog");
      attachmentScope6x = (new ItemGunAttachment(9077)).setCDItemDisplayName("Прицел x5 БР").setCDItemTextureName("6xscope");
      attachmentScope12x = (new ItemGunAttachment(9078)).setCDItemDisplayName("Прицел x10 ДР").setCDItemTextureName("12xscope");
      attachmentSupressor = (new ItemGunAttachment(9079)).addInformation("Уменьшает звук выстрела").addInformation("Уменьшает урон").setCDItemDisplayName("Глушитель").setCDItemTextureName("suppressor");
      attachmentGrip = (new ItemGunAttachment(9080)).addInformation("Увеличивает точность выстрела").setCDItemDisplayName("Тактическая рукоядка").setCDItemTextureName("grip");
      attachmentBipod = (new ItemGunAttachment(9081)).addInformation("Уменьшает разброс пуль").setCDItemDisplayName("Сошка").setCDItemTextureName("bipod");
      attachmentMuzzleBrake = (new ItemGunAttachment(9082)).addInformation("Уменьшает разброс пуль").setCDItemDisplayName("Дульный тормоз").setCDItemTextureName("muzzlebrake");
      if (true) {
	      m4a1 = (new ItemGun(9000, 600.0D, 2.0D, 1.1F, 6.3F, false)).setRepair(10000).setGunFiremodes(EnumFireMode.AUTO, EnumFireMode.BURST, EnumFireMode.SEMI).setDamage(4, 16).setLoadableClips(stanag20Rnd.itemID, stanag30Rnd.itemID, stanagDrum.itemID, stanagBox.itemID).setSoundEffects("m4a1shoot", "m4a1shootsd", "m4a1reload").setSoundLevel(1.0F).setGunRenderer(RenderM4A1.class).setAnimationFired(GunAnimationRifleFired.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.ACOG, GunAttachment.SCOPELP, GunAttachment.SCOPEHP, GunAttachment.GRIP, GunAttachment.BIPOD, GunAttachment.SURPPRESSOR, GunAttachment.MUZZLE_BRAKE).setAllowedSkins(GunPaint.CYREX, GunPaint.ASMO).setCDItemDisplayName("M4A1").setCDItemTextureName("m4a1");
	      scarh = (new ItemGun(9001, 600.0D, 3.0D, 1.2F, 7.0F, false)).setRepair(11000).setGunFiremodes(EnumFireMode.AUTO, EnumFireMode.BURST, EnumFireMode.SEMI).setDamage(5, 6).setLoadableClips(stanag20Rnd.itemID, stanag30Rnd.itemID, stanagDrum.itemID, stanagBox.itemID).setSoundEffects("scarhshoot", "m4a1shootsd", "m4a1reload").setSoundLevel(1.2F).setGunRenderer(RenderScarh.class).setAnimationFired(GunAnimationRifleFired.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.ACOG, GunAttachment.SCOPELP, GunAttachment.SCOPEHP, GunAttachment.GRIP, GunAttachment.BIPOD, GunAttachment.SURPPRESSOR, GunAttachment.MUZZLE_BRAKE).setAllowedSkins(GunPaint.ASMO).setCDItemDisplayName("Scar-H").setCDItemTextureName("scarh");
	      akm = (new ItemGun(9003, 600.0D, 3.0D, 1.5F, 9.0F, false)).setRepair(9000).setGunFiremodes(EnumFireMode.AUTO, EnumFireMode.SEMI).setDamage(5, 6).setLoadableClips(akm10rnd.itemID, akm30rnd.itemID, stanagDrum.itemID).setSoundEffects("akmshoot", "akmshootsd", "akmreload").setSoundLevel(1.5F).setGunRenderer(RenderAKM.class).setAnimationFired(GunAnimationRifleFired.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.ACOG, GunAttachment.SCOPELP, GunAttachment.SCOPEHP, GunAttachment.GRIP, GunAttachment.BIPOD, GunAttachment.SURPPRESSOR, GunAttachment.MUZZLE_BRAKE).setAllowedSkins(GunPaint.VULCAN).setCDItemDisplayName("AKM").setCDItemTextureName("akm");
	      fnfal = (new ItemGun(9004, 600.0D, 3.5D, 2.0F, 8.0F, false)).setRepair(6000).setGunFiremodes(EnumFireMode.SEMI).setDamage(5, 7).setLoadableClips(fnfalAmmo.itemID).setSoundEffects("fnfalshoot", "akmshootsd", "m4a1reload").setSoundLevel(2.0F).setGunRenderer(RenderFNFAL.class).setAnimationFired(GunAnimationRifleFired.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.ACOG, GunAttachment.SCOPELP, GunAttachment.SCOPEHP, GunAttachment.GRIP, GunAttachment.BIPOD, GunAttachment.SURPPRESSOR, GunAttachment.MUZZLE_BRAKE).setAllowedSkins().setCDItemDisplayName("FN FAL").setCDItemTextureName("fnfal");
	      m1911 = (new ItemGun(9010, 500.0D, 2.0D, 1.0F, 4.0F, true)).setRepair(3000).setGunFiremodes(EnumFireMode.SEMI).setDamage(3, 5).setLoadableClips(m1911Ammo.itemID).setSoundEffects("m1911shoot", "m1911shootsd", "m1911reload").setSoundLevel(0.8F).setGunRenderer(RenderM1911.class).setAnimationFired(GunAnimationPistolFired.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.SURPPRESSOR, GunAttachment.MUZZLE_BRAKE).setAllowedSkins().setCDItemDisplayName("M1911").setCDItemTextureName("m1911");
	      g18 = (new ItemGun(9011, 500.0D, 2.200000047683716D, 1.0F, 5.0F, true)).setRepair(4000).setGunFiremodes(EnumFireMode.AUTO, EnumFireMode.SEMI).setDamage(3, 4).setLoadableClips(g18Ammo.itemID).setSoundEffects("g18shoot", "g18shootsd", "g18reload").setSoundLevel(0.8F).setGunRenderer(RenderG18.class).setAnimationFired(GunAnimationPistolFired.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.SURPPRESSOR).setAllowedSkins(GunPaint.FADE).setCDItemDisplayName("G18").setCDItemTextureName("g18");
	      m9 = (new ItemGun(9012, 500.0D, 1.5D, 1.5F, 4.0F, true)).setGunFiremodes(EnumFireMode.SEMI).setRepair(3500).setDamage(4, 6).setLoadableClips(m9Ammo.itemID).setSoundEffects("m9shoot", "m9shootsd", "m9reload").setSoundLevel(1.0F).setGunRenderer(RenderM9.class).setAnimationFired(GunAnimationPistolFired.class).setAllowedAttachments(GunAttachment.SURPPRESSOR, GunAttachment.MUZZLE_BRAKE).setAllowedSkins().setCDItemDisplayName("M9").setCDItemTextureName("m9");
	      mac10 = (new ItemGun(9020, 600.0D, 1.7999999523162842D, 1.0F, 6.0F, true)).setRepair(6000).setGunFiremodes(EnumFireMode.AUTO).setDamage(4, 4).setLoadableClips(mac10Ammo.itemID).setSoundEffects("mac10shoot", "m4a1shootsd", "mac10reload").setSoundLevel(0.8F).setGunRenderer(RenderMAC10.class).setAnimationFired(GunAnimationSMGFired.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.ACOG, GunAttachment.SURPPRESSOR, GunAttachment.MUZZLE_BRAKE).setAllowedSkins(GunPaint.FADE, GunPaint.UV).setCDItemDisplayName("MAC-10").setCDItemTextureName("mac10");
	      p90 = (new ItemGun(9021, 600.0D, 2.200000047683716D, 1.2F, 4.0F, true)).setRepair(7500).setGunFiremodes(EnumFireMode.AUTO).setDamage(3, 4).setLoadableClips(p90Ammo.itemID).setSoundEffects("p90shoot", "p90shootsd", "p90reload").setSoundLevel(1.0F).setGunRenderer(RenderP90.class).setAnimationFired(GunAnimationSMGFired.class).setAnimationReload(GunAnimationReloadP90.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.ACOG, GunAttachment.SURPPRESSOR, GunAttachment.MUZZLE_BRAKE).setAllowedSkins(GunPaint.RUBY, GunPaint.GEM).setCDItemDisplayName("P90").setCDItemTextureName("p90");
	      sporter22 = (new ItemGun(9030, 300.0D, 1.5D, 0.8F, 5.0F, false)).setRepair(8000).setGunFiremodes(EnumFireMode.SEMI).setDamage(6, 8).setLoadableClips(sporter22Ammo.itemID).setSoundEffects("sporter22shoot", "akmshootsd", "m107reload").setSoundLevel(0.5F).setGunRenderer(RenderSporter.class).setAnimationFired(GunAnimationRifleFired.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.ACOG, GunAttachment.SCOPELP, GunAttachment.SCOPEHP, GunAttachment.GRIP, GunAttachment.BIPOD, GunAttachment.SURPPRESSOR, GunAttachment.MUZZLE_BRAKE).setAllowedSkins().setCDItemDisplayName("Sporter 22").setCDItemTextureName("sporter22");
	      m107 = (new ItemGun(9031, 120.0D, 3.0D, 1.9F, 15.0F, false)).setRepair(2000).setGunFiremodes(EnumFireMode.SEMI).setDamage(14, 18).setLoadableClips(m107Ammo.itemID, m107AmmoAP.itemID).setSoundEffects("m107shoot", "m107shootsd", "m107reload").setSoundLevel(1.8F).setGunRenderer(RenderM107.class).setAnimationFired(GunAnimationRifleFired.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.ACOG, GunAttachment.SCOPELP, GunAttachment.SCOPEHP, GunAttachment.GRIP, GunAttachment.BIPOD, GunAttachment.MUZZLE_BRAKE).setAllowedSkins(GunPaint.CandyApple).setCDItemDisplayName("M107").setCDItemTextureName("m107");
	      as50 = (new ItemGun(9032, 350.0D, 3.5D, 2.5F, 18.0F, false)).setRepair(2500).setGunFiremodes(EnumFireMode.SEMI).setDamage(12, 14).setLoadableClips(as50Ammo.itemID, as50AmmoAP.itemID).setSoundEffects("as50shoot", "as50shootsd", "as50reload").setSoundLevel(2.0F).setGunRenderer(RenderAS50.class).setAnimationFired(GunAnimationRifleFired.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.ACOG, GunAttachment.SCOPELP, GunAttachment.SCOPEHP, GunAttachment.GRIP, GunAttachment.BIPOD, GunAttachment.MUZZLE_BRAKE).setAllowedSkins(GunPaint.CandyApple).setCDItemDisplayName("AS50").setCDItemTextureName("as50");
	      m1garand = (new ItemGun(9033, 350.0D, 2.0D, 2.0F, 14.0F, false)).setRepair(6000).setGunFiremodes(EnumFireMode.SEMI).setDamage(7, 10).setLoadableClips(m1garandAmmo.itemID).setSoundEffects("m1garandshoot", "m1garandshootsd", "m1garandreload").setSoundLevel(1.5F).setGunRenderer(RenderM1Garand.class).setAnimationFired(GunAnimationRifleFired.class).setAllowedAttachments(GunAttachment.SCOPELP, GunAttachment.SCOPEHP, GunAttachment.BIPOD).setAllowedSkins().setCDItemDisplayName("M1 Garand").setCDItemTextureName("m1garand");
	      trenchgun = (new ItemGun(9040, 200.0D, 3.0D, 4.0F, 18.0F, false)).setRepair(4000).setGunFiremodes(EnumFireMode.SEMI).setDamage(2, 4).setLoadableClips(trenchgunAmmo.itemID).setSoundEffects("trenchgunshoot", "trenchgunshootsd", "shotgunreload").setSoundLevel(1.0F).setGunRenderer(RenderTrenchGun.class).setAnimationFired(GunAnimationPistolFired.class).setAllowedAttachments(GunAttachment.GRIP).setAllowedSkins().setBulletTravelDistance(15).setBulletAmountFired(8).setSpreadWhileAiming().setClipDisposable().setCDItemDisplayName("Trench Gun").setCDItemTextureName("trenchgun");
	      m240b = (new ItemGun(9045, 700.0D, 4.0D, 3.0F, 20.0F, false)).setRepair(15000).setGunFiremodes(EnumFireMode.AUTO).setDamage(4, 6).setLoadableClips(m240bAmmo.itemID).setSoundEffects("m240bshoot", "m240bshootsd", "m240breload").setSoundLevel(1.5F).setGunRenderer(RenderM240B.class).setAnimationFired(GunAnimationSMGFired.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.GRIP, GunAttachment.BIPOD, GunAttachment.MUZZLE_BRAKE).setAllowedSkins().setCDItemDisplayName("M240B").setCDItemTextureName("m240b");
	      mp5a4 = (new ItemGun(9046, 575.0D, 2.5D, 1.0F, 4.5F, false)).setRepair(15000).setGunFiremodes(EnumFireMode.AUTO, EnumFireMode.BURST, EnumFireMode.SEMI).setDamage(3, 5).setLoadableClips(mp5a4rnd.itemID).setSoundEffects("mp5a4shoot", "mp5a4shootsd", "mp5a4reload").setSoundLevel(1.5F).setGunRenderer(RenderMP5A4.class).setAllowedSkins().setAnimationFired(GunAnimationSMGFired.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.SURPPRESSOR, GunAttachment.SCOPEHP, GunAttachment.SCOPELP, GunAttachment.ACOG, GunAttachment.MUZZLE_BRAKE).setCDItemDisplayName("MP5A4").setCDItemTextureName("mp5a4");
      }
      else {
    	  m4a1 = (new ItemGun(9000, 600.0D, 2.0D, 1.1F, 6.3F, false)).setRepair(10000).setGunFiremodes(EnumFireMode.AUTO, EnumFireMode.BURST, EnumFireMode.SEMI).setDamage(7, 14).setLoadableClips(stanag20Rnd.itemID, stanag30Rnd.itemID, stanagDrum.itemID, stanagBox.itemID).setSoundEffects("m4a1shoot", "m4a1shootsd", "m4a1reload").setSoundLevel(1.0F).setGunRenderer(RenderM4A1.class).setAnimationFired(GunAnimationRifleFired.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.ACOG, GunAttachment.SCOPELP, GunAttachment.SCOPEHP, GunAttachment.GRIP, GunAttachment.BIPOD, GunAttachment.SURPPRESSOR, GunAttachment.MUZZLE_BRAKE).setAllowedSkins(GunPaint.CYREX, GunPaint.ASMO).setCDItemDisplayName("M4A1").setCDItemTextureName("m4a1");
	      scarh = (new ItemGun(9001, 600.0D, 3.0D, 1.2F, 7.0F, false)).setRepair(11000).setGunFiremodes(EnumFireMode.AUTO, EnumFireMode.BURST, EnumFireMode.SEMI).setDamage(6, 16).setLoadableClips(stanag20Rnd.itemID, stanag30Rnd.itemID, stanagDrum.itemID, stanagBox.itemID).setSoundEffects("scarhshoot", "m4a1shootsd", "m4a1reload").setSoundLevel(1.2F).setGunRenderer(RenderScarh.class).setAnimationFired(GunAnimationRifleFired.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.ACOG, GunAttachment.SCOPELP, GunAttachment.SCOPEHP, GunAttachment.GRIP, GunAttachment.BIPOD, GunAttachment.SURPPRESSOR, GunAttachment.MUZZLE_BRAKE).setAllowedSkins(GunPaint.ASMO).setCDItemDisplayName("Scar-H").setCDItemTextureName("scarh");
	      akm = (new ItemGun(9003, 600.0D, 3.0D, 1.5F, 9.0F, false)).setRepair(9000).setGunFiremodes(EnumFireMode.AUTO, EnumFireMode.SEMI).setDamage(7, 16).setLoadableClips(akm10rnd.itemID, akm30rnd.itemID, stanagDrum.itemID).setSoundEffects("akmshoot", "akmshootsd", "akmreload").setSoundLevel(1.5F).setGunRenderer(RenderAKM.class).setAnimationFired(GunAnimationRifleFired.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.ACOG, GunAttachment.SCOPELP, GunAttachment.SCOPEHP, GunAttachment.GRIP, GunAttachment.BIPOD, GunAttachment.SURPPRESSOR, GunAttachment.MUZZLE_BRAKE).setAllowedSkins(GunPaint.VULCAN).setCDItemDisplayName("AKM").setCDItemTextureName("akm");
	      fnfal = (new ItemGun(9004, 600.0D, 3.5D, 2.0F, 8.0F, false)).setRepair(6000).setGunFiremodes(EnumFireMode.SEMI).setDamage(8, 16).setLoadableClips(fnfalAmmo.itemID).setSoundEffects("fnfalshoot", "akmshootsd", "m4a1reload").setSoundLevel(2.0F).setGunRenderer(RenderFNFAL.class).setAnimationFired(GunAnimationRifleFired.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.ACOG, GunAttachment.SCOPELP, GunAttachment.SCOPEHP, GunAttachment.GRIP, GunAttachment.BIPOD, GunAttachment.SURPPRESSOR, GunAttachment.MUZZLE_BRAKE).setAllowedSkins().setCDItemDisplayName("FN FAL").setCDItemTextureName("fnfal");
	      m1911 = (new ItemGun(9010, 500.0D, 2.0D, 1.0F, 4.0F, true)).setRepair(3000).setGunFiremodes(EnumFireMode.SEMI).setDamage(5, 8).setLoadableClips(m1911Ammo.itemID).setSoundEffects("m1911shoot", "m1911shootsd", "m1911reload").setSoundLevel(0.8F).setGunRenderer(RenderM1911.class).setAnimationFired(GunAnimationPistolFired.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.SURPPRESSOR, GunAttachment.MUZZLE_BRAKE).setAllowedSkins().setCDItemDisplayName("M1911").setCDItemTextureName("m1911");
	      g18 = (new ItemGun(9011, 500.0D, 2.200000047683716D, 1.0F, 5.0F, true)).setRepair(4000).setGunFiremodes(EnumFireMode.AUTO, EnumFireMode.SEMI).setDamage(4, 7).setLoadableClips(g18Ammo.itemID).setSoundEffects("g18shoot", "g18shootsd", "g18reload").setSoundLevel(0.8F).setGunRenderer(RenderG18.class).setAnimationFired(GunAnimationPistolFired.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.SURPPRESSOR).setAllowedSkins(GunPaint.FADE).setCDItemDisplayName("G18").setCDItemTextureName("g18");
	      m9 = (new ItemGun(9012, 500.0D, 1.5D, 1.5F, 4.0F, true)).setGunFiremodes(EnumFireMode.SEMI).setRepair(3500).setDamage(6, 8).setLoadableClips(m9Ammo.itemID).setSoundEffects("m9shoot", "m9shootsd", "m9reload").setSoundLevel(1.0F).setGunRenderer(RenderM9.class).setAnimationFired(GunAnimationPistolFired.class).setAllowedAttachments(GunAttachment.SURPPRESSOR, GunAttachment.MUZZLE_BRAKE).setAllowedSkins().setCDItemDisplayName("M9").setCDItemTextureName("m9");
	      mac10 = (new ItemGun(9020, 600.0D, 1.7999999523162842D, 1.0F, 6.0F, true)).setRepair(6000).setGunFiremodes(EnumFireMode.AUTO).setDamage(5, 9).setLoadableClips(mac10Ammo.itemID).setSoundEffects("mac10shoot", "m4a1shootsd", "mac10reload").setSoundLevel(0.8F).setGunRenderer(RenderMAC10.class).setAnimationFired(GunAnimationSMGFired.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.ACOG, GunAttachment.SURPPRESSOR, GunAttachment.MUZZLE_BRAKE).setAllowedSkins(GunPaint.FADE, GunPaint.UV).setCDItemDisplayName("MAC-10").setCDItemTextureName("mac10");
	      p90 = (new ItemGun(9021, 600.0D, 2.200000047683716D, 1.2F, 4.0F, true)).setRepair(7500).setGunFiremodes(EnumFireMode.AUTO).setDamage(4, 8).setLoadableClips(p90Ammo.itemID).setSoundEffects("p90shoot", "p90shootsd", "p90reload").setSoundLevel(1.0F).setGunRenderer(RenderP90.class).setAnimationFired(GunAnimationSMGFired.class).setAnimationReload(GunAnimationReloadP90.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.ACOG, GunAttachment.SURPPRESSOR, GunAttachment.MUZZLE_BRAKE).setAllowedSkins(GunPaint.RUBY, GunPaint.GEM).setCDItemDisplayName("P90").setCDItemTextureName("p90");
	      sporter22 = (new ItemGun(9030, 300.0D, 1.5D, 0.8F, 5.0F, false)).setRepair(8000).setGunFiremodes(EnumFireMode.SEMI).setDamage(6, 14).setLoadableClips(sporter22Ammo.itemID).setSoundEffects("sporter22shoot", "akmshootsd", "m107reload").setSoundLevel(0.5F).setGunRenderer(RenderSporter.class).setAnimationFired(GunAnimationRifleFired.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.ACOG, GunAttachment.SCOPELP, GunAttachment.SCOPEHP, GunAttachment.GRIP, GunAttachment.BIPOD, GunAttachment.SURPPRESSOR, GunAttachment.MUZZLE_BRAKE).setAllowedSkins().setCDItemDisplayName("Sporter 22").setCDItemTextureName("sporter22");
	      m107 = (new ItemGun(9031, 120.0D, 3.0D, 1.9F, 15.0F, false)).setRepair(2000).setGunFiremodes(EnumFireMode.SEMI).setDamage(20, 28).setLoadableClips(m107Ammo.itemID, m107AmmoAP.itemID).setSoundEffects("m107shoot", "m107shootsd", "m107reload").setSoundLevel(1.8F).setGunRenderer(RenderM107.class).setAnimationFired(GunAnimationRifleFired.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.ACOG, GunAttachment.SCOPELP, GunAttachment.SCOPEHP, GunAttachment.GRIP, GunAttachment.BIPOD, GunAttachment.MUZZLE_BRAKE).setAllowedSkins(GunPaint.CandyApple).setCDItemDisplayName("M107").setCDItemTextureName("m107");
	      as50 = (new ItemGun(9032, 350.0D, 3.5D, 2.5F, 18.0F, false)).setRepair(2500).setGunFiremodes(EnumFireMode.SEMI).setDamage(17, 24).setLoadableClips(as50Ammo.itemID, as50AmmoAP.itemID).setSoundEffects("as50shoot", "as50shootsd", "as50reload").setSoundLevel(2.0F).setGunRenderer(RenderAS50.class).setAnimationFired(GunAnimationRifleFired.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.ACOG, GunAttachment.SCOPELP, GunAttachment.SCOPEHP, GunAttachment.GRIP, GunAttachment.BIPOD, GunAttachment.MUZZLE_BRAKE).setAllowedSkins(GunPaint.CandyApple).setCDItemDisplayName("AS50").setCDItemTextureName("as50");
	      m1garand = (new ItemGun(9033, 350.0D, 2.0D, 2.0F, 14.0F, false)).setRepair(6000).setGunFiremodes(EnumFireMode.SEMI).setDamage(10, 12).setLoadableClips(m1garandAmmo.itemID).setSoundEffects("m1garandshoot", "m1garandshootsd", "m1garandreload").setSoundLevel(1.5F).setGunRenderer(RenderM1Garand.class).setAnimationFired(GunAnimationRifleFired.class).setAllowedAttachments(GunAttachment.SCOPELP, GunAttachment.SCOPEHP, GunAttachment.BIPOD).setAllowedSkins().setCDItemDisplayName("M1 Garand").setCDItemTextureName("m1garand");
	      trenchgun = (new ItemGun(9040, 200.0D, 3.0D, 4.0F, 18.0F, false)).setRepair(4000).setGunFiremodes(EnumFireMode.SEMI).setDamage(2, 5).setLoadableClips(trenchgunAmmo.itemID).setSoundEffects("trenchgunshoot", "trenchgunshootsd", "shotgunreload").setSoundLevel(1.0F).setGunRenderer(RenderTrenchGun.class).setAnimationFired(GunAnimationPistolFired.class).setAllowedAttachments(GunAttachment.GRIP).setAllowedSkins().setBulletTravelDistance(15).setBulletAmountFired(8).setSpreadWhileAiming().setClipDisposable().setCDItemDisplayName("Trench Gun").setCDItemTextureName("trenchgun");
	      m240b = (new ItemGun(9045, 600.0D, 4.0D, 3.0F, 20.0F, false).setRepair(15000)).setGunFiremodes(EnumFireMode.AUTO).setDamage(8, 14).setLoadableClips(m240bAmmo.itemID).setSoundEffects("m240bshoot", "m240bshootsd", "m240breload").setSoundLevel(1.5F).setGunRenderer(RenderM240B.class).setAnimationFired(GunAnimationSMGFired.class).setAllowedAttachments(GunAttachment.REDDOT, GunAttachment.GRIP, GunAttachment.BIPOD, GunAttachment.MUZZLE_BRAKE).setAllowedSkins().setCDItemDisplayName("M240B").setCDItemTextureName("m240b");  
      }
      crowbar = (new ItemMeleeWeapon(9101, 3, 100)).setCDItemDisplayName("Монтировка").setCDItemTextureName("crowbar");
      bat = (new ItemMeleeWeapon(9102, 2, 55)).setCDItemDisplayName("Бейсбольная бита").setCDItemTextureName("bat");
      ninjasword = (new ItemMeleeWeapon(9103, 3, 40)).setCDItemDisplayName("Катана").setCDItemTextureName("ninjasword");
      pipe = (new ItemMeleeWeapon(9104, 2, 60)).setCDItemDisplayName("Труба").setCDItemTextureName("pipe");
      rustypipe = (new ItemMeleeWeapon(9105, 2, 20)).setCDItemDisplayName("Ржавая труба").setCDItemTextureName("rustypipe");
      fireaxe = (new ItemCDAxe(9106, 4, 100)).setAxeStrength(1.6F).setAxeDropRate(4).setCDItemDisplayName("Пожарный топор").setCDItemTextureName("axe");
      chainsaw = (new ItemMeleeWeapon(9107, 5, 75)).setCDItemDisplayName("Сломанная бензопила").setCDItemTextureName("chainsaw");
      bowie = (new ItemMeleeWeapon(9108, 4, 20)).setCDItemDisplayName("Нож боуи").setCDItemTextureName("bowie");
      golfclub = (new ItemMeleeWeapon(9109, 2, 40)).setCDItemDisplayName("Клюшка для гольфа").setCDItemTextureName("golfclub");
      nightstick = (new ItemMeleeWeapon(9110, 2, 70)).setCDItemDisplayName("Полицейская дубинка").setCDItemTextureName("nightstick");
      sludgehammer = (new ItemCDPickaxe(9111, 2, 110)).setPickaxeStrength(1.2F).setPickaxeDropRate(1).setCDItemDisplayName("Кувалда").setCDItemTextureName("sledgehammer");
      batNail = (new ItemMeleeWeapon(9112, 3, 55)).setCDItemDisplayName("Бита с гвоздями").setCDItemTextureName("batnail");
      shovel = (new ItemMeleeWeapon(9113, 2, 70)).setCDItemDisplayName("Старая лопата").setCDItemTextureName("shovel");
      hatchet = (new ItemCDAxe(9114, 3, 40)).setAxeStrength(1.2F).setAxeDropRate(2).setCDItemDisplayName("Топор").setCDItemTextureName("hatchet");
      broadsword = (new ItemMeleeWeapon(9115, 3, 55)).setCDItemDisplayName("Длинный меч").setCDItemTextureName("broadsword");
      machete = (new ItemMeleeWeapon(9116, 3, 70)).setCDItemDisplayName("Мачете").setCDItemTextureName("machete");
      scytheweapon = (new ItemMeleeWeapon(9117, 4, 40)).setCDItemDisplayName("Боевая коса").setCDItemTextureName("scytheweapon");
      scythe = (new ItemMeleeWeapon(9118, 4, 20)).setCDItemDisplayName("Коса").setCDItemTextureName("scythe");
      pickaxe = (new ItemCDPickaxe(9119, 3, 210)).setPickaxeStrength(1.6F).setPickaxeDropRate(3).setCDItemDisplayName("Шахтерская кирка").setCDItemTextureName("pickaxe");
      bostaff = (new ItemMeleeWeapon(9120, 2, 70)).setCDItemDisplayName("Посох").setCDItemTextureName("bostaff");
      wrench = (new ItemMeleeWeapon(9121, 3, 120)).setCDItemDisplayName("Ключ").setCDItemTextureName("wrench");
      fryingPan = (new ItemMeleeWeapon(9122, 4, 80)).setCDItemDisplayName("Сковорода").setCDItemTextureName("fryingpan");
      boltCutters = (new ItemBoltCutters(9123, 3, 50)).setCuttingDamage(40).setCDItemDisplayName("Болторез").setCDItemTextureName("boltcutters");
      combatKnife = (new ItemMeleeWeapon(9124, 4, 100)).setCDItemDisplayName("Боевой нож").setCDItemTextureName("combatknife");
      steelBat = (new ItemMeleeWeapon(9125, 3, 180)).setCDItemDisplayName("Стальная бита").setCDItemTextureName("steelbat");
      cleaver = (new ItemMeleeWeapon(9126, 4, 80)).setCDItemDisplayName("Мясной тесак").setCDItemTextureName("cleaver");
      powerbar = (new ItemConsumable(9150)).setEdible(4).setCDItemDisplayName("Энергетический батончик").setCDItemTextureName("powerbar");
      candybar = (new ItemConsumable(9151)).setEdible(6).setCDItemDisplayName("Сладкий батончик").setCDItemTextureName("candybar");
      cereal = (new ItemConsumable(9152)).setEdible(10).setCDItemDisplayName("Коробка хлопьев").setCDItemTextureName("cereal");
      cannedBeans = (new ItemCD(9153)).setCDItemDisplayName("Консервированные бобы").setCDItemTextureName("beans");
      cannedBeansOpen = (new ItemConsumable(9154)).setEdible(8).setCDItemDisplayName("Открытые консервированные бобы").setCDItemTextureName("beansopen");
      cannedTuna = (new ItemCD(9155)).setCDItemDisplayName("Консервированный тунец").setCDItemTextureName("tuna");
      cannedTunaOpen = (new ItemConsumable(9156)).setEdible(6).setCDItemDisplayName("Открытая Консервированный тунец").setCDItemTextureName("tunaopen");
      cannedPeach = (new ItemCD(9157)).setCDItemDisplayName("Консервированные персики").setCDItemTextureName("peach");
      cannedPeachOpen = (new ItemConsumable(9158)).setEdible(6).setDrinkable(2).setCDItemDisplayName("Открытые консервированные персики").setCDItemTextureName("peachopen");
      mre = (new ItemConsumable(9159)).setEdible(16).setDrinkable(8).setCDItemDisplayName("Сухой паек (МРЕ)").setCDItemTextureName("mre");
      orange = (new ItemConsumable(9160)).setEdible(5).setDrinkable(2).setCDItemDisplayName("Апельсин").setCDItemTextureName("orange");
      rottenOrange = (new ItemConsumable(9161)).setEdible(2).setDrinkable(1).setCDItemDisplayName("Гнилой апельсин").setCDItemTextureName("orangerotten").setPotionEffect(Potion.confusion.getName());
      pear = (new ItemConsumable(9162)).setEdible(4).setDrinkable(3).setCDItemDisplayName("Груша").setCDItemTextureName("pear");
      rottenPear = (new ItemConsumable(9163)).setEdible(1).setDrinkable(1).setCDItemDisplayName("Гнилая груша").setCDItemTextureName("pearrotten").setPotionEffect(Potion.confusion.getName());
      cannedPasta = (new ItemCD(9164)).setCDItemDisplayName("Консервированные макароны").setCDItemTextureName("pasta");
      cannedPastaOpen = (new ItemConsumable(9165)).setEdible(6).setCDItemDisplayName("Открытые консервированные макароны").setCDItemTextureName("pastaopen");
      rice = (new ItemConsumable(9166)).setEdible(8).setCDItemDisplayName("Мешок риса").setCDItemTextureName("rice");
      apple = (new ItemConsumable(9167)).setEdible(5).setDrinkable(3).setCDItemDisplayName("Яблоко").setCDItemTextureName("apple");
      rottenApple = (new ItemConsumable(9168)).setEdible(1).setDrinkable(1).setCDItemDisplayName("Гнилое яблоко").setCDItemTextureName("applerotten").setPotionEffect(Potion.confusion.getName());
      cannedBacon = (new ItemCD(9169)).setCDItemDisplayName("Консервированный бекон").setCDItemTextureName("tacticalbacon");
      cannedBaconOpen = (new ItemConsumable(9170)).setEdible(8).setCDItemDisplayName("Открытый консервированный бекон").setCDItemTextureName("tacticalbaconopen");
      noodles = (new ItemConsumable(9171)).setEdible(6).setDrinkable(4).setCDItemDisplayName("Коробка макарон").setCDItemTextureName("noodles");
      watermelon = (new ItemConsumable(9172)).setEdible(6).setDrinkable(6).setCDItemDisplayName("Кусок арбуза").setCDItemTextureName("watermelon");
      rottenWatermelon = (new ItemConsumable(9173)).setEdible(3).setDrinkable(2).setCDItemDisplayName("Гнилой кусок арбуза").setCDItemTextureName("watermelonrotten").setPotionEffect(Potion.confusion.getName());
      cannedCorn = (new ItemCD(9174)).setCDItemDisplayName("Консервированная кукуруза").setCDItemTextureName("cannedcorn");
      cannedCornOpen = (new ItemConsumable(9175)).setEdible(6).setCDItemDisplayName("Открытая консервированная кукуруза").setCDItemTextureName("cannedcornopen");
      blueberry = (new ItemConsumable(9176)).setEdible(2).setDrinkable(4).setCDItemDisplayName("Голубика").setCDItemTextureName("blueberry");
      rottenBlueberry = (new ItemConsumable(9177)).setEdible(1).setDrinkable(2).setCDItemDisplayName("Гнилая голубика").setCDItemTextureName("blueberryrotten").setPotionEffect(Potion.confusion.getName());
      raspberry = (new ItemConsumable(9178)).setEdible(3).setDrinkable(4).setCDItemDisplayName("Земляника").setCDItemTextureName("raspberry");
      rottenRaspberry = (new ItemConsumable(9179)).setEdible(1).setDrinkable(2).setCDItemDisplayName("Гнилая земляника").setCDItemTextureName("raspberryrotten").setPotionEffect(Potion.confusion.getName());
      cannedCustard = (new ItemCD(9180)).setCDItemDisplayName("Консервированный заварной крем").setCDItemTextureName("custard");
      cannedCustardOpen = (new ItemConsumable(9181)).setEdible(4).setDrinkable(4).setCDItemDisplayName("Открытый консервированный заварной крем").setCDItemTextureName("custardopen");
      teaBag = (new ItemCD(9182)).addInformation("Совмещается с фляжкой").setCDItemDisplayName("Мешочек чая").setCDItemTextureName("teabag");
      coffee = (new ItemCD(9183)).addInformation("Совмещается с фляжкой").setCDItemDisplayName("Межочек кофейных бобов").setCDItemTextureName("coffeebeans");
      cannedPickles = (new ItemCD(9184)).setCDItemDisplayName("Консервированные огурцы").setCDItemTextureName("cannedpickles");
      cannedPicklesOpen = (new ItemConsumable(9185)).setEdible(6).setCDItemDisplayName("Открытые консервированные огурцы").setCDItemTextureName("cannedpicklesopen");
      chips = (new ItemConsumable(9186)).setEdible(3).setCDItemDisplayName("Картофельные чипсы").setCDItemTextureName("chips");
      chipsRanch = (new ItemConsumable(9187)).setEdible(3).setCDItemDisplayName("Ранчо чипсы").setCDItemTextureName("chipsranch");
      chipsCheese = (new ItemConsumable(9188)).setEdible(3).setCDItemDisplayName("Сырные чипсы").setCDItemTextureName("chipscheese");
      chipsSalt = (new ItemConsumable(9189)).setEdible(3).setCDItemDisplayName("Солёные чипсы").setCDItemTextureName("chipssalt");
      sodaColaEmpty = (new ItemCD(9200)).setCDItemDisplayName("Пустая банка КОЛЫ").setCDItemTextureName("sodacolaempty");
      sodaCola = (new ItemConsumable(9201)).setDrinkable(4).setReturnItem(sodaColaEmpty.itemID).setAnimation(EnumAction.drink).setCDItemDisplayName("КОЛА").setCDItemTextureName("sodacola");
      sodaDewEmpty = (new ItemCD(9202)).setCDItemDisplayName("Пустая банка ДЬЮ").setCDItemTextureName("sodadewempty");
      sodaDew = (new ItemConsumable(9203)).setDrinkable(4).setReturnItem(sodaDewEmpty.itemID).setAnimation(EnumAction.drink).setCDItemDisplayName("ДЬЮ").setCDItemTextureName("sodadew");
      sodaPepeEmpty = (new ItemCD(9204)).setCDItemDisplayName("Пустая банка ПЕПЕ").setCDItemTextureName("sodapepeempty");
      sodaPepe = (new ItemConsumable(9205)).setDrinkable(4).setReturnItem(sodaPepeEmpty.itemID).setAnimation(EnumAction.drink).setCDItemDisplayName("ПЕПЕ").setCDItemTextureName("sodapepe");
      sodaOrangeEmpty = (new ItemCD(9206)).setCDItemDisplayName("Пустая банка апельсиновой газировки").setCDItemTextureName("sodaorangeempty");
      sodaOrange = (new ItemConsumable(9207)).setDrinkable(4).setReturnItem(sodaOrangeEmpty.itemID).setAnimation(EnumAction.drink).setCDItemDisplayName("Апельсиновая газировка").setCDItemTextureName("sodaorange");
      iceteaEmpty = (new ItemCD(9208)).setCDItemDisplayName("Пустая банка ледяного чая").setCDItemTextureName("iceteaempty");
      icetea = (new ItemConsumable(9209)).setDrinkable(4).setReturnItem(iceteaEmpty.itemID).setAnimation(EnumAction.drink).setCDItemDisplayName("Ледяной чай").setCDItemTextureName("icetea");
      juiceEmpty = (new ItemCD(9210)).setCDItemDisplayName("Пустой пакет сока").setCDItemTextureName("juiceempty");
      juice = (new ItemConsumable(9211)).setDrinkable(2).setReturnItem(juiceEmpty.itemID).setAnimation(EnumAction.drink).setCDItemDisplayName("Пакет сока").setCDItemTextureName("juice");
      waterbottleEmpty = (new ItemCD(9212)).setCDItemDisplayName("Пустая бутылка воды").setCDItemTextureName("waterbottleempty");
      waterbottle = (new ItemConsumable(9213)).setDrinkable(8).setReturnItem(waterbottleEmpty.itemID).setAnimation(EnumAction.drink).setCDItemDisplayName("Бутылка воды").setCDItemTextureName("waterbottle");
      watercanteenEmpty = (new ItemReturnable(9214, 9215)).setWaterClicked().setCDItemDisplayName("Пустая фляга").setCDItemTextureName("watercanteenempty");
      watercanteen = (new ItemConsumable(9215)).setDrinkable(9).setReturnItem(watercanteenEmpty.itemID).setAnimation(EnumAction.drink).setCDItemDisplayName("Фляга воды").setCDItemTextureName("watercanteen");
      milkEmpty = (new ItemCD(9216)).setCDItemDisplayName("Пустая бутля молока").setCDItemTextureName("milkempty");
      milk = (new ItemConsumable(9217)).setDrinkable(8).setReturnItem(milkEmpty.itemID).setAnimation(EnumAction.drink).setCDItemDisplayName("Бутля молока").setCDItemTextureName("milk");
      milkRotten = (new ItemConsumable(9218)).setDrinkable(4).setReturnItem(milkEmpty.itemID).setAnimation(EnumAction.drink).setCDItemDisplayName("Бутля скисшего молока").setCDItemTextureName("milkrotten").setPotionEffect(Potion.confusion.getName());
      flaskEmpty = (new ItemReturnable(9219, 9220)).setWaterClicked().setCDItemDisplayName("Пустая фляжка").setCDItemTextureName("flask");
      flask = (new ItemConsumable(9220)).setDrinkable(6).setReturnItem(flaskEmpty.itemID).setAnimation(EnumAction.drink).setCDItemDisplayName("Фляжка воды").setCDItemTextureName("flaskwater");
      flasktea = (new ItemConsumable(9221)).setDrinkable(7).setReturnItem(flaskEmpty.itemID).setAnimation(EnumAction.drink).addInformation("Содержит чай").setCDItemDisplayName("Фляжка чая").setCDItemTextureName("flasktea");
      flaskCoffee = (new ItemConsumable(9222)).setDrinkable(8).setReturnItem(flaskEmpty.itemID).setAnimation(EnumAction.drink).addInformation("Содержит кофе").setCDItemDisplayName("Фляжка кофе").setCDItemTextureName("flaskcoffee");
      backpackSmallRed = (new ItemBackpack(9250, EnumBackpackSize.SMALL)).setRenderer(new RenderBackpackSmall("modelbackpacksmallred", new ModelBackpackSmall())).setCDItemDisplayName("Маленький красный рюкзак").setCDItemTextureName("backpacksmallred");
      backpackSmallOrange = (new ItemBackpack(9251, EnumBackpackSize.SMALL)).setRenderer(new RenderBackpackSmall("modelbackpacksmallorange", new ModelBackpackSmall())).setCDItemDisplayName("Маленький оранжевый").setCDItemTextureName("backpacksmallorange");
      backpackSmallYellow = (new ItemBackpack(9252, EnumBackpackSize.SMALL)).setRenderer(new RenderBackpackSmall("modelbackpacksmallyellow", new ModelBackpackSmall())).setCDItemDisplayName("Маленький желтый рюкзак").setCDItemTextureName("backpacksmallyellow");
      backpackSmallGreen = (new ItemBackpack(9253, EnumBackpackSize.SMALL)).setRenderer(new RenderBackpackSmall("modelbackpacksmallgreen", new ModelBackpackSmall())).setCDItemDisplayName("Маленький зеленый рюкзак").setCDItemTextureName("backpacksmallgreen");
      backpackSmallBlue = (new ItemBackpack(9254, EnumBackpackSize.SMALL)).setRenderer(new RenderBackpackSmall("modelbackpacksmallblue", new ModelBackpackSmall())).setCDItemDisplayName("Маленький синий рюкзак").setCDItemTextureName("backpacksmallblue");
      backpackSmallPurple = (new ItemBackpack(9255, EnumBackpackSize.SMALL)).setRenderer(new RenderBackpackSmall("modelbackpacksmallpurple", new ModelBackpackSmall())).setCDItemDisplayName("Маленький фиолетовый рюкзак").setCDItemTextureName("backpacksmallpurple");
      backpackMediumRed = (new ItemBackpack(9260, EnumBackpackSize.MEDIUM)).setRenderer(new RenderBackpackMedium("modelbackpackmediumred", new ModelBackpackMedium())).setCDItemDisplayName("Средний красный рюкзак").setCDItemTextureName("backpackmediumred");
      backpackMediumOrange = (new ItemBackpack(9261, EnumBackpackSize.MEDIUM)).setRenderer(new RenderBackpackMedium("modelbackpackmediumorange", new ModelBackpackMedium())).setCDItemDisplayName("Средний оранжевый рюкзак").setCDItemTextureName("backpackmediumorange");
      backpackMediumYellow = (new ItemBackpack(9262, EnumBackpackSize.MEDIUM)).setRenderer(new RenderBackpackMedium("modelbackpackmediumyellow", new ModelBackpackMedium())).setCDItemDisplayName("Средний желтый рюкзак").setCDItemTextureName("backpackmediumyellow");
      backpackMediumGreen = (new ItemBackpack(9263, EnumBackpackSize.MEDIUM)).setRenderer(new RenderBackpackMedium("modelbackpackmediumgreen", new ModelBackpackMedium())).setCDItemDisplayName("Средний зеленый рюкзак").setCDItemTextureName("backpackmediumgreen");
      backpackMediumBlue = (new ItemBackpack(9264, EnumBackpackSize.MEDIUM)).setRenderer(new RenderBackpackMedium("modelbackpackmediumblue", new ModelBackpackMedium())).setCDItemDisplayName("Средний синий рюкзак").setCDItemTextureName("backpackmediumblue");
      backpackMediumPurple = (new ItemBackpack(9265, EnumBackpackSize.MEDIUM)).setRenderer(new RenderBackpackMedium("modelbackpackmediumpurple", new ModelBackpackMedium())).setCDItemDisplayName("Средний фиолетовый рюкзак").setCDItemTextureName("backpackmediumpurple");
      backpackMediumGrey = (new ItemBackpack(9266, EnumBackpackSize.MEDIUM)).setRenderer(new RenderBackpackMedium("modelbackpackmediumgrey", new ModelBackpackMedium())).setCDItemDisplayName("Средний серый рюкзак").setCDItemTextureName("backpackmediumgrey");
      backpackMediumBlack = (new ItemBackpack(9267, EnumBackpackSize.MEDIUM)).setRenderer(new RenderBackpackMedium("modelbackpackmediumblack", new ModelBackpackMedium())).setCDItemDisplayName("Средний черный рюкзак").setCDItemTextureName("backpackmediumblack");
      backpackMediumGhillie = (new ItemBackpack(9268, EnumBackpackSize.MEDIUM)).setRenderer(new RenderBackpackMedium("modelbackpackmediumghillie", new ModelBackpackMedium())).setCDItemDisplayName("Средний камуфляжный рюкзак").setCDItemTextureName("backpackmediumghillie");
      backpackMediumWhite = (new ItemBackpack(9269, EnumBackpackSize.MEDIUM)).setRenderer(new RenderBackpackMedium("modelbackpackmediumwhite", new ModelBackpackMedium())).setCDItemDisplayName("Средний белый рюкзак").setCDItemTextureName("backpackmediumwhite");
      backpackLargeGrey = (new ItemBackpack(9275, EnumBackpackSize.LARGE)).setRenderer(new RenderBackpackLarge("modelbackpacklargegrey", new ModelBackpackLarge())).setCDItemDisplayName("Большой серый рюкзак").setCDItemTextureName("backpacklargegrey");
      backpackLargeGreen = (new ItemBackpack(9276, EnumBackpackSize.LARGE)).setRenderer(new RenderBackpackLarge("modelbackpacklargegreen", new ModelBackpackLarge())).setCDItemDisplayName("Большой зеленый рюкзак").setCDItemTextureName("backpacklargegreen");
      backpackLargeTan = (new ItemBackpack(9277, EnumBackpackSize.LARGE)).setRenderer(new RenderBackpackLarge("modelbackpacklargetan", new ModelBackpackLarge())).setCDItemDisplayName("Большой бледный рюкзак").setCDItemTextureName("backpacklargetan");
      backpackLargeBlack = (new ItemBackpack(9278, EnumBackpackSize.LARGE)).setRenderer(new RenderBackpackLarge("modelbackpacklargeblack", new ModelBackpackLarge())).setCDItemDisplayName("Большой черный рюкзак").setCDItemTextureName("backpacklargeblack");
      backpackLargeGhillie = (new ItemBackpack(9279, EnumBackpackSize.LARGE)).setRenderer(new RenderBackpackLarge("modelbackpacklargeghillie", new ModelBackpackLarge())).setCDItemDisplayName("Большой Ghillie рюкзак").setCDItemTextureName("backpacklargeghillie");
      backpackGunBag = (new ItemBackpack(9285, EnumBackpackSize.GUNBAG)).setRenderer(new RenderBackpackGunbag("modelbackpackgunbag", new ModelBackpackGunbag())).setCDItemDisplayName("Бледный оружейный мешок").setCDItemTextureName("backpackgunbag");
      backpackGunBagGrey = (new ItemBackpack(9286, EnumBackpackSize.GUNBAG)).setRenderer(new RenderBackpackGunbag("modelbackpackgunbaggrey", new ModelBackpackGunbag())).setCDItemDisplayName("Серый оружейный мешок").setCDItemTextureName("backpackgunbaggrey");
      tacvestGrey = (new ItemTacticalVest(9290)).setRenderer(new RenderTacticalVest("modelvestgrey", new ModelTacticalVest())).setCDItemDisplayName("Серый тактический жилет").setCDItemTextureName("vestgrey");
      tacvestGreen = (new ItemTacticalVest(9291)).setRenderer(new RenderTacticalVest("modelvestgreen", new ModelTacticalVest())).setCDItemDisplayName("Зеленый тактический жилет").setCDItemTextureName("vestgreen");
      tacvestTan = (new ItemTacticalVest(9292)).setRenderer(new RenderTacticalVest("modelvesttan", new ModelTacticalVest())).setCDItemDisplayName("Бледный тактический жилет").setCDItemTextureName("vesttan");
      tacvestBlack = (new ItemTacticalVest(9293)).setRenderer(new RenderTacticalVest("modelvestblack", new ModelTacticalVest())).setCDItemDisplayName("Черный тактический жилет").setCDItemTextureName("vestblack");
      tacvestGhillie = (new ItemTacticalVest(9294)).setRenderer(new RenderTacticalVest("modelvestghillie", new ModelTacticalVest())).setCDItemDisplayName("Маскировочный тактический жилет").setCDItemTextureName("vestghillie");
      riotVest = (new ItemTacticalVest(9295)).setRenderer(new RenderTacticalVest("modelvestriot", new ModelTacticalVest())).setCDItemDisplayName("Бунтовый жилет").setCDItemTextureName("vestriot");
      fsbVest = (new ItemTacticalVest(9296)).setRenderer(new RenderTacticalVest("modelvestfsb", new ModelTacticalVest())).setCDItemDisplayName("Жилет федеральной службы безопасности").setCDItemTextureName("vestfsb");
      clothingGhillie = (new ItemClothing(9300, "ghillie")).setArmorLevel(1).setCDItemDisplayName("Тактический маскировочный костюм").setCDItemTextureName("clothingghillie");
      clothingGhillieFull = (new ItemClothing(9301, "ghilliefull")).setArmorLevel(0).setCDItemDisplayName("Полный маскировочный костюм").setCDItemTextureName("clothingghilliefull");
      clothingDusk = (new ItemClothing(9302, "dusk")).setArmorLevel(2).setCDItemDisplayName("Сумрачный Костюм").setCDItemTextureName("clothingdusk");
      clothingSwat = (new ItemClothing(9303, "swat")).setArmorLevel(3).setCDItemDisplayName("Одежда отряда спец. назначения").setCDItemTextureName("clothingswat");
      clothingArmy = (new ItemClothing(9304, "army")).setArmorLevel(3).setCDItemDisplayName("Армейская одежда").setCDItemTextureName("clothingarmy");
      clothingBusiness = (new ItemClothing(9305, "business")).setArmorLevel(0).setCDItemDisplayName("Бизнес костюм").setCDItemTextureName("clothingbusiness");
      clothingDoctor = (new ItemClothing(9306, "doctor")).setArmorLevel(0).setCDItemDisplayName("Одежда доктора").setCDItemTextureName("clothingdoctor");
      clothingHazmat = (new ItemClothing(9307, "hazmat")).setFireResistance().setArmorLevel(1).setCDItemDisplayName("Скафандр").setCDItemTextureName("clothinghazmat");
      clothingPolice = (new ItemClothing(9308, "police")).setArmorLevel(2).setCDItemDisplayName("Полицейский костюм").setCDItemTextureName("clothingpolice");
      clothingSheriff = (new ItemClothing(9309, "sheriff")).setArmorLevel(1).setCDItemDisplayName("Костюм шериффа").setCDItemTextureName("clothingsheriff");
      clothingArmyDesert = (new ItemClothing(9310, "armydesert")).setArmorLevel(3).setCDItemDisplayName("Бледный армейский костюм").setCDItemTextureName("clothingarmydesert");
      clothingFireman = (new ItemClothing(9311, "fireman")).setFireResistance().setArmorLevel(2).setCDItemDisplayName("Костюм пожарника").setCDItemTextureName("clothingfireman");
      clothingSpaceman = (new ItemClothing(9312, "spaceman")).setFireResistance().setArmorLevel(3).setCDItemDisplayName("Костюм космонавта").setCDItemTextureName("clothingspaceman");
      clothingJuggernaut = (new ItemClothingJuggernaut(9313, "juggernaut")).setArmorLevel(3).setCDItemDisplayName("Костюм джаггернаута").setCDItemTextureName("clothingjug");
      clothingCamo = (new ItemClothing(9314, "camo")).setArmorLevel(3).setCDItemDisplayName("Камуфляжный костюм").setCDItemTextureName("clothingcamo");
      clothingCasual = (new ItemClothing(9315, "casual")).setArmorLevel(0).setCDItemDisplayName("Повседневная одежда").setCDItemTextureName("clothingcasual");
      clothingSmart = (new ItemClothing(9316, "smart")).setArmorLevel(0).setCDItemDisplayName("Простая повседневная одежда").setCDItemTextureName("clothingsmart");
      clothingSpetsnaz = (new ItemClothing(9317, "spetsnaz")).setArmorLevel(3).setCDItemDisplayName("Одежда русского спецназа").setCDItemTextureName("clothingspetsnaz");
      clothingBuilder = (new ItemClothing(9318, "builder")).setArmorLevel(0).setCDItemDisplayName("Одежда строителя").setCDItemTextureName("clothingbuilder");
      clothingredCheckered = (new ItemClothing(9319, "checkedred")).setArmorLevel(0).setCDItemDisplayName("Красная майка в клетку").setCDItemTextureName("clothingredcheck");
      clothingArmyWinter = (new ItemClothing(9320, "armywinter")).setArmorLevel(3).setCDItemDisplayName("Зимний армейский костюм").setCDItemTextureName("clothingarmywinter");
      clothingCombatBDU = (new ItemClothing(9321, "combatbdu")).setArmorLevel(3).setCDItemDisplayName("Костюм боевого отряда BDU").setCDItemTextureName("clothingcombatbdu");
      clothingFSB = (new ItemClothing(9322, "fsb")).setArmorLevel(3).setCDItemDisplayName("Костюм федеральной службы безопасности").setCDItemTextureName("clothingfsb");
      defaultArmorH = (new ItemClothingArmor(9380, DEFAULT, CDAftermath.proxy.addArmor("default"), 0)).setCDItemDisplayName("CD Clothing Armor").setCDItemTextureName("defaulth");
      defaultArmorC = (new ItemClothingArmor(9381, DEFAULT, CDAftermath.proxy.addArmor("default"), 1)).setCDItemDisplayName("CD Clothing Armor").setCDItemTextureName("defaultc");
      defaultArmorL = (new ItemClothingArmor(9382, DEFAULT, CDAftermath.proxy.addArmor("default"), 2)).setCDItemDisplayName("CD Clothing Armor").setCDItemTextureName("defaultl");
      defaultArmorB = (new ItemClothingArmor(9383, DEFAULT, CDAftermath.proxy.addArmor("default"), 3)).setCDItemDisplayName("CD Clothing Armor").setCDItemTextureName("defaultb");
	  stonePebble = (new ItemCD(9450)).setCDItemDisplayName("Камешек").setCDItemTextureName("stones").setMaxStackSize(64);
      canOpener = (new ItemCanOpener(9451)).setCDItemDisplayName("Открывашка").setCDItemTextureName("canopener").setMaxDamage(14);
      logSplit = (new ItemCD(9452)).setCDItemDisplayName("Ветка дерева").setCDItemTextureName("splitlog").setMaxStackSize(64);
      pvcPipe = (new ItemCD(9453)).setCDItemDisplayName("ПВХ труба").setCDItemTextureName("pvcpipe");
      rawExplosive = (new ItemCD(9454)).setCDItemDisplayName("Сырая взрывчатка").setCDItemTextureName("rawexp");
      detonator = (new ItemC4Detonator(9455)).setCDItemDisplayName("Детонатор C4").setCDItemTextureName("c4det");
      electronicRemote = (new ItemCD(9456)).setCDItemDisplayName("Электрический сигнал").setCDItemTextureName("electronicsignal");
      c4 = (new ItemC4(9457)).setCDItemDisplayName("Взрывчатка C4").setCDItemTextureName("c4");
      fuelTankBackpack = (new ItemFuelTankBackpack(9458)).setCDItemDisplayName("Рюкзак с топливным хранилищем").setCDItemTextureName("fueltankbackpack");
      fuelTank = (new ItemFuelTank(9459, 400)).setCDItemDisplayName("Картридж топлива").setCDItemTextureName("fueltank");
      flameThrower = (new ItemFlameThrower(9460)).setCDItemDisplayName("Огнемет").setCDItemTextureName("flamethrower");
      handcuffs = (new ItemHandcuffs(9461)).setCDItemDisplayName("Наручники").setCDItemTextureName("handcuffs");
      handcuffsKey = (new ItemHandcuffsKey(9462)).setCDItemDisplayName("Ключ от наручников").setCDItemTextureName("handcuffskey");
      rope = (new ItemCD(9463)).setCDItemDisplayName("Веревка").addInformation("Создавайте шины и другое!").setCDItemTextureName("rope");
      screwdriver = (new ItemCanOpener(9467)).setCDItemDisplayName("Отвертка").setCDItemTextureName("screwdriver").setMaxDamage(22);
      chalk = (new ItemChalk(9468)).setCDItemDisplayName("Гравировочный камень").setCDItemTextureName("chalk");
      hatPayDayMask = (new ItemHat(9500)).setRenderer(new RenderHatPayday("paydaymerica")).setCDItemDisplayName("Маска Merica Pay-Day").setCDItemTextureName("hatpayday");
      hatPayDayMask2 = (new ItemHat(9501)).setRenderer(new RenderHatPayday("paydaywolf")).setCDItemDisplayName("Маска Wolf Pay-Day").setCDItemTextureName("hatpayday2");
      hatBunny = (new ItemHat(9502)).setRenderer(new RenderHatBunny()).setCDItemDisplayName("Ушки зайка").setCDItemTextureName("hatbunny");
      hatTophat = (new ItemHat(9503)).setRenderer(new RenderHatTophat()).setCDItemDisplayName("Колпак сэра").setCDItemTextureName("hattophat");
      hatArmyHelmet = (new ItemHatHelmet(9504)).setRenderer(new RenderHatArmyhelmet("armytan")).setCDItemDisplayName("Пустынный военный шлем").setCDItemTextureName("hatarmyhelmet");
      hatArmyHelmetGrey = (new ItemHatHelmet(9505)).setRenderer(new RenderHatArmyhelmet("armygrey")).setCDItemDisplayName("Городской военный шлем").setCDItemTextureName("hatarmyhelmetgrey");
      hatArmyHelmetGreen = (new ItemHatHelmet(9506)).setRenderer(new RenderHatArmyhelmet("armygreen")).setCDItemDisplayName("Лесной военный шлем").setCDItemTextureName("hatarmyhelmetgreen");
      hatGasmask = (new ItemHat(9507)).setRenderer(new RenderHatGasmask()).setReducesFlahes().setCDItemDisplayName("Противогаз").setCDItemTextureName("hatgasmask");
      hatGhillie = (new ItemHat(9508)).setRenderer(new RenderHatArmyhelmet("ghillie")).setCDItemDisplayName("Камуфляжная шляпа").setCDItemTextureName("hatghillie");
      hatHazmat = (new ItemHat(9509)).setRenderer(new RenderHatArmyhelmet("hazmat")).setReducesFlahes().setCDItemDisplayName("Маска скафандра").setCDItemTextureName("hathazmat");
      hatNVGoggles = (new ItemHat(9510)).setRenderer(new RenderHatNVGoggles()).setCDItemDisplayName("Очки ночного видения").setCDItemTextureName("hatnvgoggles").addInformation("Press " + EnumChatFormatting.RED + "'N'" + EnumChatFormatting.GRAY + " to toggle Night Vision!");
      hatDoctor = (new ItemHat(9511)).setRenderer(new RenderHatArmyhelmet("doctor")).setCDItemDisplayName("Противобактериальная маска").setCDItemTextureName("hatdoctor");
      hatKnight = (new ItemHat(9512)).setRenderer(new RenderHatKnight()).setCDItemDisplayName("Шлем война").setCDItemTextureName("hatknight");
      hatHardhatRed = (new ItemHatHelmet(9513)).setRenderer(new RenderHatHardhat("hardhatred")).setCDItemDisplayName("Красная каска").setCDItemTextureName("hathardhatred");
      hatHardhatOrange = (new ItemHatHelmet(9514)).setRenderer(new RenderHatHardhat("hardhatorange")).setCDItemDisplayName("Оранжевая каска").setCDItemTextureName("hathardhatorange");
      hatHardhatYellow = (new ItemHatHelmet(9515)).setRenderer(new RenderHatHardhat("hardhatyellow")).setCDItemDisplayName("Желтая каска").setCDItemTextureName("hathardhatyellow");
      hatHardhatGreen = (new ItemHatHelmet(9516)).setRenderer(new RenderHatHardhat("hardhatgreen")).setCDItemDisplayName("зеленая каска").setCDItemTextureName("hathardhatgreen");
      hatHardhatBlue = (new ItemHatHelmet(9517)).setRenderer(new RenderHatHardhat("hardhatblue")).setCDItemDisplayName("Синяя каска").setCDItemTextureName("hathardhatblue");
      hatFireman = (new ItemHat(9518)).setRenderer(new RenderHatFireman(true)).setCDItemDisplayName("Шляпа пожарника").setCDItemTextureName("hatfireman");
      hatFiremanBlack = (new ItemHat(9519)).setRenderer(new RenderHatFireman(false)).setCDItemDisplayName("Шляпа шеф-повара").setCDItemTextureName("hatfiremanblack");
      hatMobCreeper = (new ItemHat(9520)).setRenderer(new RenderHatPayday("mobcreeper")).setCDItemDisplayName("Маска крипера").setCDItemTextureName("hatmobcreeper");
      hatMobZombie = (new ItemHat(9521)).setRenderer(new RenderHatPayday("mobzombie")).setCDItemDisplayName("Маска зомби").setCDItemTextureName("hatmobzombie");
      hatMobCow = (new ItemHat(9522)).setRenderer(new RenderHatPayday("mobcow")).setCDItemDisplayName("Маска коровы").setCDItemTextureName("hatmobcow");
      hatMobPumpkin = (new ItemHat(9523)).setRenderer(new RenderHatPayday("mobpumpkin")).setCDItemDisplayName("Маска тыквы").setCDItemTextureName("hatmobpumpkin");
      hatRiot = (new ItemHatHelmet(9524)).setRenderer(new RenderHatArmyhelmet("riot")).setCDItemDisplayName("Военный шлем-каска").setCDItemTextureName("hatriot");
      hatSanta = (new ItemHat(9525)).setRenderer(new RenderHatArmyhelmet("santa")).setCDItemDisplayName("Шапка санты").setCDItemTextureName("hatsanta");
      hatMobSheep = (new ItemHat(9526)).setRenderer(new RenderHatPayday("mobsheep")).setCDItemDisplayName("Маска овцы").setCDItemTextureName("hatmobsheep");
      hatCamoHelmet = (new ItemHatHelmet(9527)).setRenderer(new RenderHatArmyhelmet("camo")).setCDItemDisplayName("Камуфляжный шлем").setCDItemTextureName("hatcamo");
      hatSpetsnazHelmet = (new ItemHatHelmet(9528)).setRenderer(new RenderHatArmyhelmet("spetsnaz")).setCDItemDisplayName("Шлем русского спецназа").setCDItemTextureName("hatspetsnaz");
      hatCombatBDU = (new ItemHatHelmet(9529)).setRenderer(new RenderHatArmyhelmet("combatbdu")).setCDItemDisplayName("Шлем боевого отряда BDU").setCDItemTextureName("hatcombatbdu");
      hatFSB = (new ItemHatHelmet(9530)).setRenderer(new RenderHatArmyhelmet("fsb")).setCDItemDisplayName("Шлем федеральной службы безопасности").setCDItemTextureName("hatfsb");
      paintAsmo = (new ItemPaint(9600, GunPaint.ASMO)).setCDItemDisplayName("Краска ASMO").setCDItemTextureName("paintasmo");
      paintCyrex = (new ItemPaint(9601, GunPaint.CYREX)).setCDItemDisplayName("Краска Cyrex").setCDItemTextureName("paintcyrex");
      paintVulcan = (new ItemPaint(9602, GunPaint.VULCAN)).setCDItemDisplayName("Краска Vulcan").setCDItemTextureName("paintvulcan");
      paintGem = (new ItemPaint(9603, GunPaint.GEM)).setCDItemDisplayName("Краска Gem").setCDItemTextureName("paintgem");
      paintRuby = (new ItemPaint(9604, GunPaint.RUBY)).setCDItemDisplayName("Краска Ruby").setCDItemTextureName("paintruby");
      paintUV = (new ItemPaint(9605, GunPaint.UV)).setCDItemDisplayName("Краска UV").setCDItemTextureName("paintuv");
      paintFade = (new ItemPaint(9606, GunPaint.FADE)).setCDItemDisplayName("Краска Fade").setCDItemTextureName("paintfade");
      paintCandyApple = (new ItemPaint(9607, GunPaint.CandyApple)).setCDItemDisplayName("Краска Candy Apple").setCDItemTextureName("paintcandyapple");
      grenadeFlash = (new ItemGrenadeFlash(9650)).setCDItemDisplayName("Ослепляющая граната").setCDItemTextureName("flashbang");
      grenadeDecoy = (new ItemGrenadeDecoy(9651)).setCDItemDisplayName("Граната-приманка").setCDItemTextureName("decoy");
      grenadeSmoke = (new ItemGrenadeSmoke(9652)).setCDItemDisplayName("Дымовая шашка").setCDItemTextureName("smoke");
      grenadeFire = (new ItemGrenadeFire(9653)).setCDItemDisplayName("Огненная граната").setCDItemTextureName("firebomb");
      grenadeFrag = (new ItemGrenade(9654)).setCDItemDisplayName("Граната").setCDItemTextureName("frag");
      grenadePipeBomb = (new ItemGrenadePipeBomb(9655)).addInformation("Больше фитиль чем у гранаты").setCDItemDisplayName("Бомба из трубы").setCDItemTextureName("pipebomb");
      bloodbagEmpy = (new ItemReturnableBloodBag(9675, 9676)).setPlayerClicked().setCDItemDisplayName("Пустой пакет крови").setCDItemTextureName("bloodbagempty");
      bloodbag = (new ItemConsumable(9676)).setBloodRestoreable(4).setReturnItem(bloodbagEmpy.itemID).setAnimation(EnumAction.block).setCDItemDisplayName("Пакет крови").setCDItemTextureName("bloodbag");
      bandage = (new ItemConsumable(9677)).setBloodRestoreable(2).setStopsBleeding().setAnimation(EnumAction.block).setCDItemDisplayName("Бинт").setCDItemTextureName("bandage");
      medpack = (new ItemConsumable(9678)).setBloodRestoreable(8).setStopsBleeding().setAnimation(EnumAction.block).setCDItemDisplayName("Медицинский набор").setCDItemTextureName("medpack");
      needle = (new ItemReturnable(9679, 9686)).setZombieClicked(25).setCDItemDisplayName("Пустой шприц").setCDItemTextureName("needleempty");
      needleMorphine = (new ItemConsumable(9680)).setBrokenLegFixed().setAnimation(EnumAction.block).setCDItemDisplayName("Шприц морфина").setCDItemTextureName("needlemorphine");
      needleCure = (new ItemConsumable(9681)).setCuresInfection().setAnimation(EnumAction.block).setCDItemDisplayName("Шприц вакцины RBI").setCDItemTextureName("needlecure");
      bottleCure = (new ItemCD(9682)).setCDItemDisplayName("Бутылированная вакцина RBI").setCDItemTextureName("bottlecure");
      ragDirty = (new ItemReturnable(9683, 9684)).setWaterClicked().setCDItemDisplayName("Грязная тряпка").setCDItemTextureName("ragdirty");
      ragClean = (new ItemConsumable(9684)).setStopsBleeding().setAnimation(EnumAction.block).setCDItemDisplayName("Чистая тряпка").setCDItemTextureName("ragclean");
      splint = (new ItemConsumable(9685)).setBrokenLegFixed().setAnimation(EnumAction.block).setCDItemDisplayName("Шина").setCDItemTextureName("splint");
      needleRBI = (new ItemCD(9686)).setCDItemDisplayName("Шприц с инфекцией RBI").setCDItemTextureName("needlerbi");
      bottleRBI = (new ItemCD(9687)).setCDItemDisplayName("Бутылированная инфекция RBI").setCDItemTextureName("bottlerbi");
      needleAdrenaline = (new ItemConsumable(9688)).addAdrenalineFactor().setAnimation(EnumAction.block).setCDItemDisplayName("Шприц адреналина").setCDItemTextureName("needleadrenaline");
      lootcrateAlpha = (new ItemLootcrate(9464)).addContent(m4a1, 8).addContent(mac10, 8).addContent(grenadeFrag, 4).addContent(fireaxe, 5).addContent(ninjasword, 5).addContent(mre, 2).addContent(watercanteen, 2).addContent(medpack, 3).addContent(needleCure, 3).addContent(clothingGhillieFull, 7).addContent(clothingArmyDesert, 7).addContent(backpackMediumGrey, 4).addContent(c4, 3).setCDItemDisplayName("Кейс Alpha").setCDItemTextureName("cratealpha");
      lootcrateBravo = (new ItemLootcrate(9465)).addContent(akm, 8).addContent(as50, 8).addContent(grenadeFire, 4).addContent(wrench, 5).addContent(nightstick, 5).addContent(cannedBaconOpen, 2).addContent(waterbottle, 2).addContent(bandage, 3).addContent(needleMorphine, 3).addContent(clothingJuggernaut, 7).addContent(clothingBusiness, 7).addContent(backpackLargeGrey, 4).addContent(detonator, 3).setCDItemDisplayName("Кейс Bravo").setCDItemTextureName("cratebravo");
      lootcrateCharlie = (new ItemLootcrate(9466)).addContent(m240b, 8).addContent(m9, 8).addContent(grenadeFlash, 4).addContent(steelBat, 5).addContent(pickaxe, 5).addContent(apple, 2).addContent(flask, 2).addContent(splint, 3).addContent(needleAdrenaline, 3).addContent(clothingSwat, 7).addContent(clothingDusk, 7).addContent(backpackMediumOrange, 4).addContent(handcuffs, 3).setCDItemDisplayName("Кейс Charlie").setCDItemTextureName("cratecharlie");
      bush = (new ItemSpecials(9467).setCDItemDisplayName("Куски куста").setCDItemTextureName("bush1").addInformation("Можно повесить на себя или оружие").setMaxStackSize(1));
      silver = (new ItemSpecials(9469).setCDItemDisplayName("Серебряная крышка").setCDItemTextureName("silver").setMaxStackSize(64));
      gold = (new ItemSpecials(9470).setCDItemDisplayName("Золотая крышка").setCDItemTextureName("gold").setMaxStackSize(64));
   }

   public void addCraftingRecipes() {
      GameRegistry.registerCraftingHandler(new CraftingEvents());
      GameRegistry.addRecipe(new ItemStack(splint), new Object[]{"X# ", "#X#", " #X", '#', logSplit, 'X', ragDirty});
      GameRegistry.addRecipe(new ItemStack(splint), new Object[]{"X# ", "#X#", " #X", '#', logSplit, 'X', ragClean});
      GameRegistry.addRecipe(new ItemStack(grenadePipeBomb), new Object[]{"X", "Y", "Z", 'X', electronicRemote, 'Y', rawExplosive, 'Z', pvcPipe});
      GameRegistry.addRecipe(new ItemStack(c4), new Object[]{" X ", "XYX", " X ", 'X', rawExplosive, 'Y', electronicRemote});
      GameRegistry.addRecipe(new ItemStack(splint), new Object[]{" XY", "XYX", "YX ", 'X', logSplit, 'Y', rope});
      GameRegistry.addShapelessRecipe(new ItemStack(needleCure), new Object[]{needle, bottleCure});
      GameRegistry.addShapelessRecipe(new ItemStack(needleRBI), new Object[]{needle, bottleRBI});
      GameRegistry.addShapelessRecipe(new ItemStack(flasktea), new Object[]{teaBag, flask});
      GameRegistry.addShapelessRecipe(new ItemStack(flaskCoffee), new Object[]{coffee, flask});
      this.addCannedRecipe(cannedCornOpen, cannedCorn);
      this.addCannedRecipe(cannedBeansOpen, cannedBeans);
      this.addCannedRecipe(cannedTunaOpen, cannedTuna);
      this.addCannedRecipe(cannedPeachOpen, cannedPeach);
      this.addCannedRecipe(cannedPastaOpen, cannedPasta);
      this.addCannedRecipe(cannedBaconOpen, cannedBacon);
      this.addCannedRecipe(cannedCustardOpen, cannedCustard);
      this.addCannedRecipe(cannedPicklesOpen, cannedPickles);
      this.addInfectedAmmoRecipe(stanag20Rnd);
      this.addInfectedAmmoRecipe(stanag30Rnd);
      this.addInfectedAmmoRecipe(stanagDrum);
      this.addInfectedAmmoRecipe(stanagBox);
      this.addInfectedAmmoRecipe(akm10rnd);
      this.addInfectedAmmoRecipe(akm30rnd);
      this.addInfectedAmmoRecipe(m1911Ammo);
      this.addInfectedAmmoRecipe(g18Ammo);
      this.addInfectedAmmoRecipe(mac10Ammo);
      this.addInfectedAmmoRecipe(p90Ammo);
      this.addInfectedAmmoRecipe(sporter22Ammo);
      this.addInfectedAmmoRecipe(m107Ammo);
      Item[] var1 = Item.itemsList;
      int var2 = var1.length;

      for(int var3 = 0; var3 < var2; ++var3) {
         Item item = var1[var3];
         if (item != null && (item instanceof ItemGun || item instanceof ItemMeleeWeapon || item instanceof ItemBackpack || item instanceof ItemTacticalVest)) {
            GameRegistry.addShapelessRecipe(new ItemStack(item), new Object[]{chalk, new ItemStack(item.itemID, 1, 32767)});
         }
      }

   }

   public void addCannedRecipe(Item par1Result, Item par2Required) {
      GameRegistry.addShapelessRecipe(new ItemStack(par1Result), new Object[]{par2Required, new ItemStack(canOpener, 1, 32767)});
      GameRegistry.addShapelessRecipe(new ItemStack(par1Result), new Object[]{par2Required, new ItemStack(screwdriver, 1, 32767)});
   }

   public void addInfectedAmmoRecipe(Item par1Result) {
      GameRegistry.addShapelessRecipe(new ItemStack(par1Result), new Object[]{needleRBI, new ItemStack(par1Result.itemID, 1, 32767)});
   }

   public void init() {
      LanguageRegistry.instance().addStringLocalization("itemGroup.cda", "Crafting Dead Aftermath EDIT");
      LanguageRegistry.instance().addStringLocalization("itemGroup.cdainv", "CDA Инвентарь");
      this.initItems();
      this.addCraftingRecipes();
      this.lootManager = new LootManager();
      this.lootManager.init();
      this.potionManager = new PotionManager();
      this.potionManager.init();
   }

   public LootManager getLootManager() {
      return this.lootManager;
   }

   public PotionManager getPotionManager() {
      return this.potionManager;
   }

   static {
      destroyableAxeIDs = new int[]{Block.planks.blockID, Block.chest.blockID, Block.doorWood.blockID, 1226, 1227};
      destroyablePickaxeIDs = new int[]{Block.stoneBrick.blockID, 1225, 1228};
      DEFAULT = EnumHelper.addArmorMaterial("DEFAULT", 24, new int[]{3, 7, 5, 2}, 5);
   }
}
