package by.fxg.craftingdead.item;

import by.fxg.craftingdead.block.LootType;

public class LootManager {
   //public static LootType LOOT_RESIDENTIAL;
   //public static LootType LOOT_RESIDENTIAL_RARE;
   //public static LootType LOOT_MEDICAL;
   //public static LootType LOOT_MILITARY;
   //public static LootType LOOT_POLICE;
   
   public static LootType 
   poor,
   palatkas,
   foodshop,
   clothshop,
   city,
   badcity,
   medical,
   military,
   smilitary;

   public void init() {
      //LOOT_RESIDENTIAL = (new LootType("residential", "Residential", 70.0D)).addContent(ItemManager.clothingBusiness, 20.0D).addContent(ItemManager.clothingDoctor, 20.0D).addContent(ItemManager.clothingSmart, 20.0D).addContent(ItemManager.clothingCasual, 20.0D).addContent(ItemManager.clothingredCheckered, 20.0D).addContent(ItemManager.paintRuby, 10.0D).addContent(ItemManager.paintGem, 10.0D).addContent(ItemManager.paintCandyApple, 10.0D).addContent(ItemManager.bandage, 20.0D).addContent(ItemManager.needle, 10.0D).addContent(ItemManager.ragDirty, 50.0D).addContent(ItemManager.ragClean, 10.0D).addContent(ItemManager.backpackSmallRed, 10.0D).addContent(ItemManager.backpackSmallOrange, 10.0D).addContent(ItemManager.backpackSmallYellow, 10.0D).addContent(ItemManager.backpackSmallGreen, 10.0D).addContent(ItemManager.backpackSmallBlue, 10.0D).addContent(ItemManager.backpackSmallPurple, 10.0D).addContent(ItemManager.backpackMediumGrey, 5.0D).addContent(ItemManager.hatBunny, 40.0D).addContent(ItemManager.hatFireman, 40.0D).addContent(ItemManager.hatHardhatBlue, 40.0D).addContent(ItemManager.hatHardhatGreen, 40.0D).addContent(ItemManager.hatHardhatOrange, 40.0D).addContent(ItemManager.hatHardhatRed, 40.0D).addContent(ItemManager.hatHardhatYellow, 40.0D).addContent(ItemManager.hatKnight, 40.0D).addContent(ItemManager.hatMobCow, 40.0D).addContent(ItemManager.hatMobCreeper, 40.0D).addContent(ItemManager.hatMobPumpkin, 40.0D).addContent(ItemManager.hatMobZombie, 40.0D).addContent(ItemManager.hatPayDayMask, 40.0D).addContent(ItemManager.hatPayDayMask2, 40.0D).addContent(ItemManager.hatTophat, 40.0D).addContent(ItemManager.hatSanta, 40.0D).addContent(ItemManager.hatMobSheep, 40.0D).addContent(ItemManager.sodaCola, 40.0D).addContent(ItemManager.sodaColaEmpty, 70.0D).addContent(ItemManager.sodaDew, 40.0D).addContent(ItemManager.sodaDewEmpty, 70.0D).addContent(ItemManager.sodaPepe, 20.0D).addContent(ItemManager.sodaPepeEmpty, 70.0D).addContent(ItemManager.sodaOrange, 30.0D).addContent(ItemManager.sodaOrangeEmpty, 70.0D).addContent(ItemManager.icetea, 30.0D).addContent(ItemManager.iceteaEmpty, 60.0D).addContent(ItemManager.sodaOrange, 30.0D).addContent(ItemManager.sodaOrangeEmpty, 70.0D).addContent(ItemManager.juice, 30.0D).addContent(ItemManager.juiceEmpty, 90.0D).addContent(ItemManager.waterbottle, 20.0D).addContent(ItemManager.waterbottleEmpty, 40.0D).addContent(ItemManager.milk, 10.0D).addContent(ItemManager.milkEmpty, 30.0D).addContent(ItemManager.milkRotten, 20.0D).addContent(ItemManager.watercanteen, 10.0D).addContent(ItemManager.watercanteenEmpty, 40.0D).addContent(ItemManager.flask, 10.0D).addContent(ItemManager.flaskEmpty, 40.0D).addContent(ItemManager.powerbar, 50.0D).addContent(ItemManager.candybar, 50.0D).addContent(ItemManager.cereal, 30.0D).addContent(ItemManager.cannedBeans, 70.0D).addContent(ItemManager.cannedBeansOpen, 20.0D).addContent(ItemManager.cannedTuna, 70.0D).addContent(ItemManager.cannedTunaOpen, 20.0D).addContent(ItemManager.cannedPeach, 70.0D).addContent(ItemManager.cannedPeachOpen, 20.0D).addContent(ItemManager.mre, 10.0D).addContent(ItemManager.orange, 20.0D).addContent(ItemManager.rottenOrange, 50.0D).addContent(ItemManager.apple, 20.0D).addContent(ItemManager.rottenApple, 50.0D).addContent(ItemManager.pear, 20.0D).addContent(ItemManager.rottenPear, 50.0D).addContent(ItemManager.watermelon, 20.0D).addContent(ItemManager.rottenWatermelon, 50.0D).addContent(ItemManager.rice, 30.0D).addContent(ItemManager.noodles, 50.0D).addContent(ItemManager.cannedBacon, 70.0D).addContent(ItemManager.cannedBaconOpen, 30.0D).addContent(ItemManager.cannedCorn, 70.0D).addContent(ItemManager.cannedCornOpen, 30.0D).addContent(ItemManager.blueberry, 20.0D).addContent(ItemManager.rottenBlueberry, 50.0D).addContent(ItemManager.raspberry, 20.0D).addContent(ItemManager.rottenRaspberry, 50.0D).addContent(ItemManager.cannedCustard, 70.0D).addContent(ItemManager.cannedCustardOpen, 20.0D).addContent(ItemManager.cannedPickles, 30.0D).addContent(ItemManager.cannedPicklesOpen, 20.0D).addContent(ItemManager.canOpener, 50.0D).addContent(ItemManager.electronicRemote, 10.0D).addContent(ItemManager.pvcPipe, 30.0D).addContent(ItemManager.crowbar, 10.0D).addContent(ItemManager.bat, 50.0D).addContent(ItemManager.pipe, 30.0D).addContent(ItemManager.rustypipe, 30.0D).addContent(ItemManager.fireaxe, 10.0D).addContent(ItemManager.chainsaw, 20.0D).addContent(ItemManager.nightstick, 10.0D).addContent(ItemManager.golfclub, 60.0D).addContent(ItemManager.sludgehammer, 30.0D).addContent(ItemManager.shovel, 50.0D).addContent(ItemManager.hatchet, 30.0D).addContent(ItemManager.machete, 20.0D).addContent(ItemManager.scytheweapon, 10.0D).addContent(ItemManager.scythe, 30.0D).addContent(ItemManager.bostaff, 60.0D).addContent(ItemManager.wrench, 50.0D).addContent(ItemManager.fryingPan, 50.0D).addContent(ItemManager.boltCutters, 50.0D).addContent(ItemManager.steelBat, 50.0D).addContent(ItemManager.cleaver, 50.0D).addContent(ItemManager.blueprint, 30.0D).addContent(ItemManager.m1911Ammo, 10.0D).addContent(ItemManager.mac10Ammo, 10.0D).addContent(ItemManager.g18, 10.0D).addContent(ItemManager.attachmentGrip, 10.0D).addContent(ItemManager.attachmentReddot, 10.0D).addContent(ItemManager.m1garandAmmo, 15.0D).addContent(ItemManager.m1911, 5.0D).addContent(ItemManager.g18, 5.0D).addContent(ItemManager.mac10, 5.0D).addContent(ItemManager.coffee, 50.0D).addContent(ItemManager.teaBag, 50.0D).addContent(ItemManager.rope, 50.0D);
      //LOOT_RESIDENTIAL_RARE = (new LootType("residentialrare", "Rare Residential", 40.0D)).addContent(ItemManager.clothingDusk, 20.0D).addContent(ItemManager.clothingHazmat, 20.0D).addContent(ItemManager.clothingFireman, 20.0D).addContent(ItemManager.clothingGhillie, 10.0D).addContent(ItemManager.clothingSpaceman, 5.0D).addContent(ItemManager.paintRuby, 10.0D).addContent(ItemManager.paintGem, 10.0D).addContent(ItemManager.paintUV, 10.0D).addContent(ItemManager.paintFade, 10.0D).addContent(ItemManager.paintCandyApple, 10.0D).addContent(ItemManager.paintFade, 5.0D).addContent(ItemManager.paintAsmo, 5.0D).addContent(ItemManager.paintCyrex, 5.0D).addContent(ItemManager.paintVulcan, 5.0D).addContent(ItemManager.paintFade, 5.0D).addContent(ItemManager.paintCandyApple, 5.0D).addContent(ItemManager.bandage, 30.0D).addContent(ItemManager.needle, 20.0D).addContent(ItemManager.ragDirty, 40.0D).addContent(ItemManager.ragClean, 20.0D).addContent(ItemManager.backpackMediumRed, 10.0D).addContent(ItemManager.backpackMediumOrange, 10.0D).addContent(ItemManager.backpackMediumYellow, 10.0D).addContent(ItemManager.backpackMediumGreen, 10.0D).addContent(ItemManager.backpackMediumBlue, 10.0D).addContent(ItemManager.backpackMediumPurple, 10.0D).addContent(ItemManager.backpackMediumGrey, 10.0D).addContent(ItemManager.backpackMediumBlack, 10.0D).addContent(ItemManager.backpackMediumGhillie, 5.0D).addContent(ItemManager.backpackLargeGrey, 5.0D).addContent(ItemManager.backpackLargeTan, 5.0D).addContent(ItemManager.hatFireman, 40.0D).addContent(ItemManager.hatFiremanBlack, 40.0D).addContent(ItemManager.hatPayDayMask2, 40.0D).addContent(ItemManager.hatTophat, 40.0D).addContent(ItemManager.hatArmyHelmet, 40.0D).addContent(ItemManager.hatArmyHelmetGreen, 40.0D).addContent(ItemManager.hatArmyHelmetGrey, 40.0D).addContent(ItemManager.hatGasmask, 40.0D).addContent(ItemManager.hatRiot, 40.0D).addContent(ItemManager.hatCamoHelmet, 40.0D).addContent(ItemManager.hatSpetsnazHelmet, 40.0D).addContent(ItemManager.hatCombatBDU, 40.0D).addContent(ItemManager.sodaCola, 60.0D).addContent(ItemManager.sodaDew, 60.0D).addContent(ItemManager.sodaPepe, 60.0D).addContent(ItemManager.sodaOrange, 60.0D).addContent(ItemManager.icetea, 60.0D).addContent(ItemManager.sodaOrange, 60.0D).addContent(ItemManager.juice, 60.0D).addContent(ItemManager.waterbottle, 50.0D).addContent(ItemManager.waterbottleEmpty, 50.0D).addContent(ItemManager.milk, 40.0D).addContent(ItemManager.milkEmpty, 40.0D).addContent(ItemManager.milkRotten, 40.0D).addContent(ItemManager.watercanteen, 20.0D).addContent(ItemManager.watercanteenEmpty, 30.0D).addContent(ItemManager.flask, 10.0D).addContent(ItemManager.flaskEmpty, 40.0D).addContent(ItemManager.canOpener, 50.0D).addContent(ItemManager.electronicRemote, 20.0D).addContent(ItemManager.rawExplosive, 15.0D).addContent(ItemManager.fuelTankBackpack, 20.0D).addContent(ItemManager.fuelTank, 25.0D).addContent(ItemManager.flameThrower, 5.0D).addContent(ItemManager.cereal, 40.0D).addContent(ItemManager.cannedBeansOpen, 50.0D).addContent(ItemManager.cannedPeachOpen, 50.0D).addContent(ItemManager.mre, 20.0D).addContent(ItemManager.orange, 50.0D).addContent(ItemManager.apple, 60.0D).addContent(ItemManager.pear, 50.0D).addContent(ItemManager.watermelon, 60.0D).addContent(ItemManager.rice, 20.0D).addContent(ItemManager.cannedBaconOpen, 60.0D).addContent(ItemManager.cannedCornOpen, 60.0D).addContent(ItemManager.blueberry, 40.0D).addContent(ItemManager.raspberry, 30.0D).addContent(ItemManager.cannedCustardOpen, 50.0D).addContent(ItemManager.cannedPickles, 30.0D).addContent(ItemManager.cannedPicklesOpen, 40.0D).addContent(ItemManager.crowbar, 60.0D).addContent(ItemManager.fireaxe, 40.0D).addContent(ItemManager.chainsaw, 50.0D).addContent(ItemManager.nightstick, 60.0D).addContent(ItemManager.sludgehammer, 60.0D).addContent(ItemManager.shovel, 60.0D).addContent(ItemManager.hatchet, 40.0D).addContent(ItemManager.machete, 50.0D).addContent(ItemManager.scytheweapon, 30.0D).addContent(ItemManager.ninjasword, 20.0D).addContent(ItemManager.bostaff, 30.0D).addContent(ItemManager.wrench, 60.0D).addContent(ItemManager.boltCutters, 50.0D).addContent(ItemManager.blueprint, 50.0D).addContent(ItemManager.blueprintBaseCenter, 10.0D).addContent(ItemManager.blueprintBook, 20.0D).addContent(ItemManager.grenadeDecoy, 30.0D).addContent(ItemManager.grenadeSmoke, 30.0D).addContent(ItemManager.grenadeFrag, 30.0D).addContent(ItemManager.stanag20Rnd, 10.0D).addContent(ItemManager.stanag30Rnd, 10.0D).addContent(ItemManager.akm10rnd, 10.0D).addContent(ItemManager.m9Ammo, 40.0D).addContent(ItemManager.attachmentGrip, 30.0D).addContent(ItemManager.attachmentBipod, 30.0D).addContent(ItemManager.attachmentReddot, 20.0D).addContent(ItemManager.attachmentACOG, 10.0D).addContent(ItemManager.m1garandAmmo, 20.0D).addContent(ItemManager.m1911, 5.0D).addContent(ItemManager.m9, 10.0D).addContent(ItemManager.g18, 5.0D).addContent(ItemManager.p90, 5.0D).addContent(ItemManager.m1garand, 10.0D).addContent(ItemManager.lootcrateAlpha, 20.0D).addContent(ItemManager.lootcrateBravo, 20.0D).addContent(ItemManager.lootcrateCharlie, 20.0D).addContent(ItemManager.coffee, 50.0D).addContent(ItemManager.teaBag, 50.0D).addContent(ItemManager.chalk, 60.0D).addContent(ItemManager.rope, 50.0D);
      //LOOT_MEDICAL = (new LootType("medical", "Medical", 50.0D)).addContent(ItemManager.clothingDoctor, 20.0D).addContent(ItemManager.clothingHazmat, 20.0D).addContent(ItemManager.backpackMediumRed, 10.0D).addContent(ItemManager.backpackMediumWhite, 10.0D).addContent(ItemManager.backpackSmallRed, 20.0D).addContent(ItemManager.waterbottle, 50.0D).addContent(ItemManager.powerbar, 30.0D).addContent(ItemManager.mre, 30.0D).addContent(ItemManager.hatDoctor, 40.0D).addContent(ItemManager.hatHazmat, 40.0D).addContent(ItemManager.bloodbag, 40.0D).addContent(ItemManager.bloodbagEmpy, 50.0D).addContent(ItemManager.bandage, 60.0D).addContent(ItemManager.medpack, 40.0D).addContent(ItemManager.needle, 60.0D).addContent(ItemManager.needleAdrenaline, 20.0D).addContent(ItemManager.needleMorphine, 40.0D).addContent(ItemManager.needleCure, 20.0D).addContent(ItemManager.needleRBI, 20.0D).addContent(ItemManager.bottleRBI, 10.0D).addContent(ItemManager.bottleCure, 50.0D).addContent(ItemManager.ragDirty, 70.0D).addContent(ItemManager.ragClean, 50.0D);
      //LOOT_MILITARY = (new LootType("military", "Military", 30.0D)).addContent(ItemManager.clothingDusk, 10.0D).addContent(ItemManager.clothingArmy, 30.0D).addContent(ItemManager.clothingArmyDesert, 30.0D).addContent(ItemManager.clothingGhillie, 20.0D).addContent(ItemManager.clothingGhillieFull, 10.0D).addContent(ItemManager.clothingSpaceman, 5.0D).addContent(ItemManager.clothingJuggernaut, 20.0D).addContent(ItemManager.clothingCamo, 30.0D).addContent(ItemManager.clothingSpetsnaz, 30.0D).addContent(ItemManager.clothingCombatBDU, 20.0D).addContent(ItemManager.rawExplosive, 25.0D).addContent(ItemManager.detonator, 30.0D).addContent(ItemManager.electronicRemote, 20.0D).addContent(ItemManager.fuelTankBackpack, 30.0D).addContent(ItemManager.fuelTank, 35.0D).addContent(ItemManager.flameThrower, 10.0D).addContent(ItemManager.paintFade, 10.0D).addContent(ItemManager.paintAsmo, 10.0D).addContent(ItemManager.paintCyrex, 10.0D).addContent(ItemManager.paintVulcan, 10.0D).addContent(ItemManager.paintFade, 10.0D).addContent(ItemManager.paintCandyApple, 10.0D).addContent(ItemManager.backpackLargeGrey, 20.0D).addContent(ItemManager.backpackLargeGreen, 30.0D).addContent(ItemManager.backpackLargeTan, 30.0D).addContent(ItemManager.backpackLargeBlack, 20.0D).addContent(ItemManager.backpackLargeGhillie, 20.0D).addContent(ItemManager.backpackGunBag, 10.0D).addContent(ItemManager.backpackGunBagGrey, 10.0D).addContent(ItemManager.tacvestBlack, 30.0D).addContent(ItemManager.tacvestGhillie, 5.0D).addContent(ItemManager.tacvestGrey, 20.0D).addContent(ItemManager.tacvestTan, 20.0D).addContent(ItemManager.tacvestGreen, 10.0D).addContent(ItemManager.riotVest, 10.0D).addContent(ItemManager.hatArmyHelmet, 40.0D).addContent(ItemManager.hatArmyHelmetGreen, 40.0D).addContent(ItemManager.hatArmyHelmetGrey, 40.0D).addContent(ItemManager.hatGhillie, 40.0D).addContent(ItemManager.hatHazmat, 40.0D).addContent(ItemManager.hatRiot, 40.0D).addContent(ItemManager.hatNVGoggles, 40.0D).addContent(ItemManager.hatCamoHelmet, 40.0D).addContent(ItemManager.hatSpetsnazHelmet, 40.0D).addContent(ItemManager.hatCombatBDU, 40.0D).addContent(ItemManager.waterbottle, 50.0D).addContent(ItemManager.watercanteenEmpty, 30.0D).addContent(ItemManager.sodaPepe, 50.0D).addContent(ItemManager.flask, 10.0D).addContent(ItemManager.flaskEmpty, 40.0D).addContent(ItemManager.mre, 50.0D).addContent(ItemManager.attachmentGrip, 70.0D).addContent(ItemManager.attachmentBipod, 70.0D).addContent(ItemManager.attachmentReddot, 50.0D).addContent(ItemManager.attachmentACOG, 40.0D).addContent(ItemManager.attachmentScope6x, 30.0D).addContent(ItemManager.attachmentScope12x, 20.0D).addContent(ItemManager.stanag20Rnd, 60.0D).addContent(ItemManager.stanag30Rnd, 40.0D).addContent(ItemManager.stanagDrum, 30.0D).addContent(ItemManager.stanagBox, 20.0D).addContent(ItemManager.akm10rnd, 70.0D).addContent(ItemManager.akm30rnd, 40.0D).addContent(ItemManager.m1911Ammo, 50.0D).addContent(ItemManager.g18Ammo, 50.0D).addContent(ItemManager.m9Ammo, 70.0D).addContent(ItemManager.mac10Ammo, 50.0D).addContent(ItemManager.p90Ammo, 50.0D).addContent(ItemManager.sporter22Ammo, 50.0D).addContent(ItemManager.m107Ammo, 50.0D).addContent(ItemManager.m107AmmoAP, 20.0D).addContent(ItemManager.as50Ammo, 50.0D).addContent(ItemManager.as50AmmoAP, 20.0D).addContent(ItemManager.fnfalAmmo, 50.0D).addContent(ItemManager.m1garandAmmo, 50.0D).addContent(ItemManager.m240bAmmo, 20.0D).addContent(ItemManager.trenchgunAmmo, 30.0D).addContent(ItemManager.grenadeFire, 40.0D).addContent(ItemManager.grenadeFlash, 40.0D).addContent(ItemManager.grenadeFrag, 40.0D).addContent(ItemManager.m4a1, 30.0D).addContent(ItemManager.scarh, 25.0D).addContent(ItemManager.akm, 20.0D).addContent(ItemManager.m1911, 50.0D).addContent(ItemManager.g18, 50.0D).addContent(ItemManager.m9, 60.0D).addContent(ItemManager.mac10, 40.0D).addContent(ItemManager.p90, 40.0D).addContent(ItemManager.sporter22, 70.0D).addContent(ItemManager.m107, 10.0D).addContent(ItemManager.as50, 10.0D).addContent(ItemManager.fnfal, 40.0D).addContent(ItemManager.m1garand, 60.0D).addContent(ItemManager.m240b, 10.0D).addContent(ItemManager.trenchgun, 20.0D).addContent(ItemManager.combatKnife, 30.0D);
      //LOOT_POLICE = (new LootType("police", "Police", 50.0D)).addContent(ItemManager.clothingPolice, 30.0D).addContent(ItemManager.clothingSheriff, 10.0D).addContent(ItemManager.clothingFireman, 30.0D).addContent(ItemManager.clothingSwat, 20.0D).addContent(ItemManager.clothingJuggernaut, 5.0D).addContent(ItemManager.paintFade, 10.0D).addContent(ItemManager.detonator, 10.0D).addContent(ItemManager.rawExplosive, 25.0D).addContent(ItemManager.fuelTankBackpack, 10.0D).addContent(ItemManager.fuelTank, 15.0D).addContent(ItemManager.flameThrower, 5.0D).addContent(ItemManager.handcuffs, 35.0D).addContent(ItemManager.handcuffsKey, 30.0D).addContent(ItemManager.bandage, 60.0D).addContent(ItemManager.ragClean, 30.0D).addContent(ItemManager.medpack, 30.0D).addContent(ItemManager.backpackMediumBlack, 20.0D).addContent(ItemManager.backpackMediumGrey, 20.0D).addContent(ItemManager.backpackMediumBlue, 20.0D).addContent(ItemManager.backpackLargeGrey, 10.0D).addContent(ItemManager.backpackLargeBlack, 10.0D).addContent(ItemManager.backpackGunBagGrey, 5.0D).addContent(ItemManager.tacvestBlack, 10.0D).addContent(ItemManager.tacvestGhillie, 5.0D).addContent(ItemManager.tacvestGrey, 15.0D).addContent(ItemManager.tacvestTan, 15.0D).addContent(ItemManager.tacvestGreen, 5.0D).addContent(ItemManager.riotVest, 10.0D).addContent(ItemManager.hatArmyHelmet, 40.0D).addContent(ItemManager.hatArmyHelmetGreen, 40.0D).addContent(ItemManager.hatArmyHelmetGrey, 40.0D).addContent(ItemManager.hatRiot, 40.0D).addContent(ItemManager.hatFireman, 40.0D).addContent(ItemManager.hatFiremanBlack, 40.0D).addContent(ItemManager.hatCamoHelmet, 40.0D).addContent(ItemManager.hatSpetsnazHelmet, 40.0D).addContent(ItemManager.crowbar, 50.0D).addContent(ItemManager.fireaxe, 40.0D).addContent(ItemManager.nightstick, 70.0D).addContent(ItemManager.bat, 50.0D).addContent(ItemManager.boltCutters, 50.0D).addContent(ItemManager.combatKnife, 30.0D).addContent(ItemManager.waterbottle, 50.0D).addContent(ItemManager.waterbottleEmpty, 60.0D).addContent(ItemManager.watercanteenEmpty, 40.0D).addContent(ItemManager.sodaPepe, 20.0D).addContent(ItemManager.sodaPepeEmpty, 60.0D).addContent(ItemManager.flask, 10.0D).addContent(ItemManager.flaskEmpty, 40.0D).addContent(ItemManager.powerbar, 50.0D).addContent(ItemManager.mre, 30.0D).addContent(ItemManager.attachmentGrip, 60.0D).addContent(ItemManager.attachmentBipod, 60.0D).addContent(ItemManager.attachmentReddot, 40.0D).addContent(ItemManager.attachmentACOG, 30.0D).addContent(ItemManager.attachmentScope6x, 10.0D).addContent(ItemManager.stanag20Rnd, 60.0D).addContent(ItemManager.stanag30Rnd, 40.0D).addContent(ItemManager.akm10rnd, 70.0D).addContent(ItemManager.m1911Ammo, 50.0D).addContent(ItemManager.g18Ammo, 50.0D).addContent(ItemManager.sporter22Ammo, 50.0D).addContent(ItemManager.m9Ammo, 80.0D).addContent(ItemManager.grenadeFlash, 30.0D).addContent(ItemManager.grenadeFrag, 30.0D).addContent(ItemManager.grenadeSmoke, 30.0D).addContent(ItemManager.m4a1, 10.0D).addContent(ItemManager.m1911, 60.0D).addContent(ItemManager.g18, 60.0D).addContent(ItemManager.m9, 80.0D).addContent(ItemManager.sporter22, 50.0D);
   
      poor = (new LootType("poor", "Poor", 90D))
    		  .addContent(ItemManager.g18, 10.0D)
    		  .addContent(ItemManager.m1911, 15.0D)
    		  .addContent(ItemManager.g18Ammo, 20.0D)
    		  .addContent(ItemManager.m1911Ammo, 20.0D)
    		  .addContent(ItemManager.nightstick, 50.0D)
    		  .addContent(ItemManager.bat, 45.0D)
    		  .addContent(ItemManager.screwdriver, 45.0D)
    		  .addContent(ItemManager.cannedCorn, 50.0D)
    		  .addContent(ItemManager.rottenRaspberry, 50.0D)
    		  .addContent(ItemManager.rottenWatermelon, 50.0D)
    		  .addContent(ItemManager.rottenBlueberry, 50.0D)
    		  .addContent(ItemManager.icetea, 48.0D)
    		  .addContent(ItemManager.waterbottleEmpty, 45.0D)
    		  .addContent(ItemManager.flaskEmpty, 30.0D)
    		  .addContent(ItemManager.ragClean, 39.0D)
    		  .addContent(ItemManager.splint, 30.0D)
    		  .addContent(ItemManager.grenadeDecoy, 5.0D)
    		  .addContent(ItemManager.bandage, 30.0D)
    		  .addContent(ItemManager.stonePebble, 55.0D)
    		  .addContent(ItemManager.pvcPipe, 50.0D)
    		  .addContent(ItemManager.clothingFireman, 15.0D)
    		  .addContent(ItemManager.clothingDoctor, 40.0D)
    		  .addContent(ItemManager.clothingBusiness, 40.0D)
    		  .addContent(ItemManager.clothingGhillieFull, 20.0D)
    		  .addContent(ItemManager.clothingCasual, 40.0D)
    		  .addContent(ItemManager.clothingSmart, 40.0D)
    		  .addContent(ItemManager.backpackSmallPurple, 30.0D)
    		  .addContent(ItemManager.backpackSmallBlue, 30.0D)
    		  .addContent(ItemManager.backpackMediumOrange, 20.0D)
    		  .addContent(ItemManager.backpackLargeGreen, 10.0D)
    		  .addContent(ItemManager.backpackMediumRed, 20.0D)
    		  .addContent(ItemManager.hatMobSheep, 25.0D)
    		  .addContent(ItemManager.hatMobPumpkin, 25.0D)
    		  .addContent(ItemManager.hatHardhatRed, 15.0D);
      palatkas = (new LootType("palatkas", "Palatkas", 80D))
    		  .addContent(ItemManager.g18, 10.0D)
    		  .addContent(ItemManager.g18Ammo, 15.0D)
    		  .addContent(ItemManager.akm10rnd, 5.0D)
    		  .addContent(ItemManager.mac10Ammo, 10.0D)
    		  .addContent(ItemManager.mac10, 5.0D)
    		  .addContent(ItemManager.m1garandAmmo, 10.0D)
    		  .addContent(ItemManager.m1garand, 5.0D)
    		  .addContent(ItemManager.golfclub, 30.0D)
    		  .addContent(ItemManager.batNail, 30.0D)
    		  .addContent(ItemManager.canOpener, 35.0D)
    		  .addContent(ItemManager.cannedBacon, 40.0D)
    		  .addContent(ItemManager.raspberry, 40.0D)
    		  .addContent(ItemManager.blueberry, 40.0D)
    		  .addContent(ItemManager.sodaColaEmpty, 35.0D)
    		  .addContent(ItemManager.icetea, 40.0D)
    		  .addContent(ItemManager.milkRotten, 30.0D)
    		  .addContent(ItemManager.flaskEmpty, 20.0D)
    		  .addContent(ItemManager.medpack, 5.0D)
    		  .addContent(ItemManager.bandage, 20.0D)
    		  .addContent(ItemManager.grenadeSmoke, 5.0D)
    		  .addContent(ItemManager.pvcPipe, 50.0D)
    		  .addContent(ItemManager.logSplit, 60.0D)
    		  .addContent(ItemManager.stonePebble, 60.0D)
    		  .addContent(ItemManager.clothingPolice, 20.0D)
    		  .addContent(ItemManager.clothingGhillieFull, 30.0D)
    		  .addContent(ItemManager.clothingBusiness, 40.0D)
    		  .addContent(ItemManager.clothingDoctor, 35.0D)
    		  .addContent(ItemManager.clothingCasual, 40.0D)
    		  .addContent(ItemManager.clothingSmart, 40.0D)
    		  .addContent(ItemManager.clothingBuilder, 35.0D)
    		  .addContent(ItemManager.clothingredCheckered, 35.0D)
    		  .addContent(ItemManager.backpackSmallGreen, 20.0D)
    		  .addContent(ItemManager.backpackSmallYellow, 16.0D)
    		  .addContent(ItemManager.backpackSmallOrange, 15.0D)
    		  .addContent(ItemManager.backpackMediumWhite, 11.0D)
    		  .addContent(ItemManager.backpackMediumYellow, 12.0D)
    		  .addContent(ItemManager.backpackMediumOrange, 10.0D)
    		  .addContent(ItemManager.backpackLargeGrey, 5.0D)
    		  .addContent(ItemManager.hatMobCow, 25.0D)
    		  .addContent(ItemManager.hatHardhatOrange, 15.0D);
      foodshop = (new LootType("foodshop", "Foodshop", 70D))
    		  .addContent(ItemManager.teaBag, 30.0D)
    		  .addContent(ItemManager.coffee, 30.0D)
    		  .addContent(ItemManager.cannedBeans, 40.0D)
    		  .addContent(ItemManager.cannedTuna, 40.0D)
    		  .addContent(ItemManager.chips, 35.0D)
    		  .addContent(ItemManager.chipsCheese, 35.0D)
    		  .addContent(ItemManager.chipsRanch, 35.0D)
    		  .addContent(ItemManager.chipsSalt, 35.0D)
    		  .addContent(ItemManager.noodles, 30.0D)
    		  .addContent(ItemManager.watermelon, 40.0D)
    		  .addContent(ItemManager.apple, 40.0D)
    		  .addContent(ItemManager.pear, 40.0D)
    		  .addContent(ItemManager.waterbottle, 35.0D)
    		  .addContent(ItemManager.juice, 35.0D)
    		  .addContent(ItemManager.juiceEmpty, 30.0D)
    		  .addContent(ItemManager.iceteaEmpty, 35.0D)
    		  .addContent(ItemManager.sodaOrange, 40.0D)
    		  .addContent(ItemManager.sodaPepeEmpty, 35.0D)
    		  .addContent(ItemManager.milk, 30.0D)
    		  .addContent(ItemManager.milkEmpty, 30.0D)
    		  .addContent(ItemManager.flask, 20.0D)
    		  .addContent(ItemManager.flaskCoffee, 20.0D)
    		  .addContent(ItemManager.flasktea, 20.0D)
    		  .addContent(ItemManager.flaskEmpty, 21.0D)
    		  .addContent(ItemManager.bandage, 22.0D)
    		  .addContent(ItemManager.bloodbag, 16.0D)
    		  .addContent(ItemManager.grenadeFrag, 5.0D);
      clothshop = (new LootType("clothshop", "Clothshop", 60D))
    		  .addContent(ItemManager.bandage, 20.0D)
    		  .addContent(ItemManager.grenadeSmoke, 10.0D)
    		  .addContent(ItemManager.grenadePipeBomb, 15.0D)
    		  .addContent(ItemManager.hatMobCreeper, 30.0D)
    		  .addContent(ItemManager.hatMobZombie, 30.0D)
    		  .addContent(ItemManager.hatBunny, 40.0D)
    		  .addContent(ItemManager.hatKnight, 30.0D)
    		  .addContent(ItemManager.hatTophat, 30.0D)
    		  .addContent(ItemManager.hatHardhatYellow, 25.0D);
      city = (new LootType("city", "City", 50D))
    		  .addContent(ItemManager.m1garand, 2.0D)
    		  .addContent(ItemManager.sodaOrangeEmpty, 40.0D)
    		  .addContent(ItemManager.rottenOrange, 40.0D)
    		  .addContent(ItemManager.hatPayDayMask2, 30.0D)
    		  .addContent(ItemManager.shovel, 30.0D)
    		  .addContent(ItemManager.orange, 40.0D)
    		  .addContent(ItemManager.hatPayDayMask, 20.0D)
    		  .addContent(ItemManager.backpackLargeTan, 20.0D)
    		  .addContent(ItemManager.backpackMediumBlack, 25.0D)
    		  .addContent(ItemManager.sporter22, 2.0D)
    		  .addContent(ItemManager.clothingDusk, 20.0D)
    		  .addContent(ItemManager.canOpener, 30.0D)
    		  .addContent(ItemManager.flask, 30.0D)
    		  .addContent(ItemManager.flaskEmpty, 30.0D)
    		  .addContent(ItemManager.hatHardhatGreen, 25.0D)
    		  .addContent(ItemManager.cannedPeach, 40.0D)
    		  //.addContent(ItemManager.hat, .0D) CHEIF HAT
    		  .addContent(ItemManager.hatRiot, 25.0D)
    		  .addContent(ItemManager.g18, 10.0D)
    		  .addContent(ItemManager.m1911, 10.0D)
    		  .addContent(ItemManager.bat, 25.0D)
    		  .addContent(ItemManager.stanag20Rnd, 5.0D)
    		  .addContent(ItemManager.g18Ammo, 15.0D)
    		  .addContent(ItemManager.m1911Ammo, 15.0D)
    		  .addContent(ItemManager.cannedPasta, 40.0D)
    		  .addContent(ItemManager.backpackSmallRed, 40.0D)
    		  .addContent(ItemManager.backpackMediumGhillie, 25.0D)
    		  .addContent(ItemManager.bloodbag, 20.0D)
    		  .addContent(ItemManager.medpack, 20.0D)
    		  .addContent(ItemManager.grenadeFrag, 5.0D)
    		  .addContent(ItemManager.clothingSheriff, 25.0D)
    		  .addContent(ItemManager.clothingDoctor, 35.0D)
    		  .addContent(ItemManager.clothingBusiness, 35.0D)
    		  .addContent(ItemManager.clothingSmart, 35.0D)
    		  .addContent(ItemManager.backpackMediumPurple, 30.0D)
    		  .addContent(ItemManager.backpackMediumBlue, 30.0D)
    		  .addContent(ItemManager.backpackMediumGreen, 30.0D)
    		  .addContent(ItemManager.backpackLargeBlack, 15.0D)
    		  .addContent(ItemManager.tacvestGhillie, 10.0D)
    		  .addContent(ItemManager.backpackGunBagGrey, 5.0D)
    		  .addContent(ItemManager.hatFireman, 20.0D)
    		  .addContent(ItemManager.hatGhillie, 15.0D)
    		  .addContent(ItemManager.hatHardhatBlue, 25.0D)
    		  .addContent(ItemManager.clothingPolice, 20.0D)
    		  .addContent(ItemManager.sodaDew, 40.0D)
    		  .addContent(ItemManager.rawExplosive, 15.0D)
    		  .addContent(ItemManager.bandage, 30.0D)
    		  .addContent(ItemManager.attachmentReddot, 10.0D)
    		  .addContent(ItemManager.m1garandAmmo, 5.0D)
    		  .addContent(ItemManager.backpackMediumGrey, 25.0D)
    		  .addContent(ItemManager.screwdriver, 20.0D);
      badcity = (new LootType("badcity", "Badcity", 40D))
    		  .addContent(ItemManager.m1911, 10.0D)
    		  .addContent(ItemManager.m1911Ammo, 15.0D)
    		  .addContent(ItemManager.akm10rnd, 10.0D)
    		  .addContent(ItemManager.trenchgunAmmo, 12.0D)
    		  .addContent(ItemManager.trenchgun, 7.0D)
    		  .addContent(ItemManager.fuelTank, 12.0D)
    		  .addContent(ItemManager.attachmentReddot, 11.0D)
    		  .addContent(ItemManager.batNail, 15.0D)
    		  .addContent(ItemManager.golfclub, 16.0D)
    		  .addContent(ItemManager.fryingPan, 14.0D)
    		  .addContent(ItemManager.canOpener, 20.0D)
    		  .addContent(ItemManager.boltCutters, 17.0D)
    		  .addContent(ItemManager.cannedCustard, 40.0D)
    		  .addContent(ItemManager.cannedPickles, 40.0D)
    		  .addContent(ItemManager.rottenPear, 30.0D)
    		  .addContent(ItemManager.rottenApple, 30.0D)
    		  .addContent(ItemManager.sodaDewEmpty, 30.0D)
    		  .addContent(ItemManager.sodaCola, 30.0D)
    		  .addContent(ItemManager.flaskEmpty, 20.0D)
    		  .addContent(ItemManager.bandage, 25.0D)
    		  .addContent(ItemManager.ragClean, 27.0D)
    		  .addContent(ItemManager.ragDirty, 35.0D)
    		  .addContent(ItemManager.bloodbagEmpy, 25.0D)
    		  .addContent(ItemManager.grenadePipeBomb, 10.0D)
    		  .addContent(ItemManager.stonePebble, 25.0D)
    		  .addContent(ItemManager.pvcPipe, 25.0D)
    		  .addContent(ItemManager.logSplit, 25.0D);
      medical = (new LootType("medical", "Medical", 30D))
    		  .addContent(ItemManager.rice, 40.0D)
    		  .addContent(ItemManager.cereal, 40.0D)
    		  .addContent(ItemManager.flask, 30.0D)
    		  .addContent(ItemManager.flaskEmpty, 30.0D)
    		  .addContent(ItemManager.medpack, 25.0D)
    		  .addContent(ItemManager.bloodbag, 25.0D)
    		  .addContent(ItemManager.ragClean, 25.0D)
    		  .addContent(ItemManager.ragDirty, 30.0D)
    		  .addContent(ItemManager.splint, 27.0D)
    		  .addContent(ItemManager.bloodbagEmpy, 27.0D)
    		  .addContent(ItemManager.bandage, 30.0D)
    		  .addContent(ItemManager.needleAdrenaline, 15.0D)
    		  .addContent(ItemManager.needleCure, 10.0D)
    		  .addContent(ItemManager.needleMorphine, 20.0D)
    		  .addContent(ItemManager.needle, 25.0D)
    		  .addContent(ItemManager.bottleCure, 17.0D)
    		  .addContent(ItemManager.rope, 30.0D)
    		  .addContent(ItemManager.rawExplosive, 25.0D)
    		  .addContent(ItemManager.pvcPipe, 25.0D)
    		  .addContent(ItemManager.clothingHazmat, 20.0D)
    		  .addContent(ItemManager.clothingGhillie, 25.0D)
    		  .addContent(ItemManager.backpackMediumYellow, 25.0D)
    		  .addContent(ItemManager.hatDoctor, 30.0D)
    		  .addContent(ItemManager.hatHazmat, 29.0D);
      military = (new LootType("military", "Military", 20D))
    		  .addContent(ItemManager.m9, 20.0D)
    		  .addContent(ItemManager.m9Ammo, 40.0D)
    		  .addContent(ItemManager.akm10rnd, 40.0D)
    		  .addContent(ItemManager.stanag20Rnd, 35.0D)
    		  .addContent(ItemManager.akm30rnd, 30.0D)
    		  .addContent(ItemManager.akm, 10.0D)
    		  .addContent(ItemManager.m4a1, 12.0D)
    		  .addContent(ItemManager.stanag30Rnd, 20.0D)
    		  .addContent(ItemManager.fnfal, 15.0D)
    		  .addContent(ItemManager.fnfalAmmo, 20.0D)
    		  .addContent(ItemManager.p90, 17.0D)
    		  .addContent(ItemManager.p90Ammo, 22.0D)
    		  .addContent(ItemManager.as50, 5.0D)
    		  .addContent(ItemManager.as50Ammo, 7.0D)
    		  .addContent(ItemManager.trenchgun, 22.0D)
    		  .addContent(ItemManager.trenchgunAmmo, 30.0D)
    		  .addContent(ItemManager.fuelTank, 28.0D)
    		  .addContent(ItemManager.flameThrower, 4.0D)
    		  .addContent(ItemManager.attachmentSupressor, 10.0D)
    		  .addContent(ItemManager.attachmentScope6x, 8.0D)
    		  .addContent(ItemManager.attachmentACOG, 10.0D)
    		  .addContent(ItemManager.boltCutters, 30.0D)
    		  .addContent(ItemManager.handcuffs, 5.0D)
    		  .addContent(ItemManager.mre, 30.0D)
    		  .addContent(ItemManager.candybar, 50.0D)
    		  .addContent(ItemManager.powerbar, 50.0D)
    		  .addContent(ItemManager.watercanteen, 40.0D)
    		  .addContent(ItemManager.watercanteenEmpty, 45.0D)
    		  .addContent(ItemManager.splint, 40.0D)
    		  .addContent(ItemManager.ragClean, 40.0D)
    		  .addContent(ItemManager.bandage, 38.0D)
    		  .addContent(ItemManager.needleCure, 30.0D)
    		  .addContent(ItemManager.needleAdrenaline, 32.0D)
    		  .addContent(ItemManager.grenadeFlash, 20.0D)
    		  .addContent(ItemManager.grenadeFrag, 25.0D)
    		  .addContent(ItemManager.electronicRemote, 30.0D)
    		  .addContent(ItemManager.clothingArmyWinter, 15.0D)
    		  .addContent(ItemManager.clothingCamo, 15.0D)
    		  .addContent(ItemManager.clothingArmy, 15.0D)
    		  .addContent(ItemManager.clothingGhillie, 30.0D)
    		  .addContent(ItemManager.backpackLargeGhillie, 20.0D)
    		  .addContent(ItemManager.riotVest, 15.0D)
    		  .addContent(ItemManager.tacvestBlack, 20.0D)
    		  .addContent(ItemManager.tacvestTan, 20.0D)
    		  .addContent(ItemManager.backpackGunBagGrey, 15.0D)
    		  //.addContent(ItemManager., .0D) TAN GUN BAG BACKPACK
    		  .addContent(ItemManager.hatGasmask, 18.0D)
    		  .addContent(ItemManager.hatNVGoggles, 18.0D)
    		  .addContent(ItemManager.hatArmyHelmet, 15.0D)
    		  .addContent(ItemManager.hatArmyHelmetGreen, 15.0D)
      		  .addContent(ItemManager.hatArmyHelmetGrey, 15.0D);
      smilitary = (new LootType("smilitary", "SMilitary", 10D))
    		  .addContent(ItemManager.m9, 30.0D)
    		  .addContent(ItemManager.m9Ammo, 40.0D)
    		  .addContent(ItemManager.stanagDrum, 15.0D)
    		  .addContent(ItemManager.stanagBox, 10.0D)
    		  .addContent(ItemManager.scarh, 15.0D)
    		  .addContent(ItemManager.m4a1, 22.0D)
    		  .addContent(ItemManager.akm, 22.0D)
    		  .addContent(ItemManager.m107AmmoAP, 5.0D)
    		  .addContent(ItemManager.as50AmmoAP, 5.0D)
    		  .addContent(ItemManager.m107, 3.0D)
    		  .addContent(ItemManager.m107Ammo, 10.0D)
    		  .addContent(ItemManager.m240b, 4.0D)
    		  .addContent(ItemManager.m240bAmmo, 12.0D)
    		  .addContent(ItemManager.fuelTankBackpack, 5.0D)
    		  .addContent(ItemManager.fuelTank, 20.0D)
    		  .addContent(ItemManager.flameThrower, 15.0D)
    		  .addContent(ItemManager.attachmentGrip, 20.0D)
    		  .addContent(ItemManager.attachmentSupressor, 20.0D)
    		  .addContent(ItemManager.attachmentScope12x, 10.0D)
    		  .addContent(ItemManager.attachmentACOG, 18.0D)
    		  .addContent(ItemManager.paintFade, 1.0D)
    		  .addContent(ItemManager.paintUV, 1.0D)
    		  .addContent(ItemManager.attachmentBipod, 20.0D)
    		  .addContent(ItemManager.handcuffs, 15.0D)
    		  .addContent(ItemManager.handcuffsKey, 15.0D)
    		  .addContent(ItemManager.chalk, 1.0D)
    		  .addContent(ItemManager.mre, 30.0D)
    		  .addContent(ItemManager.watercanteen, 30.0D)
    		  .addContent(ItemManager.bloodbag, 32.0D)
    		  .addContent(ItemManager.medpack, 33.0D)
    		  .addContent(ItemManager.splint, 34.0D)
    		  .addContent(ItemManager.ragClean, 40.0D)
    		  .addContent(ItemManager.bandage, 35.0D)
    		  .addContent(ItemManager.needleRBI, 10.0D)
    		  .addContent(ItemManager.bottleRBI, 10.0D)
    		  .addContent(ItemManager.needleAdrenaline, 30.0D)
    		  .addContent(ItemManager.needleCure, 25.0D)
    		  .addContent(ItemManager.bottleCure, 25.0D)
    		  .addContent(ItemManager.grenadeFrag, 30.0D)
    		  .addContent(ItemManager.grenadeFire, 15.0D)
    		  .addContent(ItemManager.grenadeDecoy, 20.0D)
    		  .addContent(ItemManager.grenadeFlash, 15.0D)
    		  .addContent(ItemManager.grenadeSmoke, 15.0D)
    		  .addContent(ItemManager.c4, 10.0D)
    		  .addContent(ItemManager.detonator, 15.0D)
    		  .addContent(ItemManager.electronicRemote, 30.0D)
    		  .addContent(ItemManager.clothingSwat, 20.0D)
    		  .addContent(ItemManager.clothingJuggernaut, 20.0D)
    		  .addContent(ItemManager.clothingSpaceman, .0D)
    		  .addContent(ItemManager.clothingCombatBDU, 20.0D)
    		  .addContent(ItemManager.clothingSpetsnaz, 20.0D)
    		  .addContent(ItemManager.backpackLargeGhillie, 30.0D)
    		  .addContent(ItemManager.riotVest, 25.0D)
    		  .addContent(ItemManager.tacvestGrey, 30.0D)
    		  .addContent(ItemManager.tacvestGreen, 30.0D)
    		  .addContent(ItemManager.backpackGunBag, 25.0D)
    		  .addContent(ItemManager.hatNVGoggles, 35.0D)
    		  .addContent(ItemManager.hatGasmask, 35.0D)
    		  .addContent(ItemManager.hatSpetsnazHelmet, 40.0D)
    		  .addContent(ItemManager.hatCamoHelmet, 35.0D)
    		  .addContent(ItemManager.hatCombatBDU, 20.0D)
    		  .addContent(ItemManager.attachmentMuzzleBrake, 10.0D);
   }
}
